### ISSUE TITLE
background link detection

### ISSUE THREAD

**Issue by jonasman** [TTTAttributedLabel/TTTAttributedLabel#150]
Hi, what do you think of a property to enable a "background link detection" that similarly to nimbus would redraw the control after the link detection is done?

This would really speed up the control drawing time when there are links to be parsed.

**Comment by om-ha** [comment]
@Jonasman This is 5 years late, but how did you fix this?

**Comment by jonasman** [comment]
With the try catch.
I think i also removed this control after a while

**Comment by om-ha** [comment]
@jonasman Really appreciate the quick response. Considering the OP is years old.

My original problem is that I have to wait for the background task to update links inside the tttlabel. Which is weird considering I added the link manually with `(void)addLink:(TTTAttributedLabelLink *)link` with a *specified range*.

I'm calling this many times in a UITableView with reusable cells. Sometimes the links show correctly as soon as UITableViewCell is displayed, other times you have to scroll the cell out of view then back in... Quite unpredictable and tricky to fix.
