### ISSUE TITLE
TextColor and TextAlignment doesn't work

### ISSUE THREAD

**Issue by mladjan** [TTTAttributedLabel/TTTAttributedLabel#253]
I tried just to dropIn replace UILabel with TTTAttributedLabel, and I have a problem with:
- Text color - this doesn't work:  [textlabel setTextColor:[UIColor whiteColor]];
  it always display black color
- Text alignment - this doesn't work: textlabel.textAlignment = NSTextAlignmentRight;
  It's always aligned left.

There is a work around for this two things?

**Comment by ZubairShah** [comment]
what about alignment TextAlignment? RTL isn't supported.
