### ISSUE TITLE
Unable to tap hyperlink

### ISSUE THREAD

**Issue by sanketfirodiya** [TTTAttributedLabel/TTTAttributedLabel#266]
The label is not tappable as a hyperlink.
I am creating the label inside a custom UITableViewCell using the following piece of code. 

messageLabel = [[TTTAttributedLabel alloc] initWithFrame:CGRectZero];

messageLabel.linkAttributes = [NSDictionary dictionaryWithObject:[NSNumber numberWithBool:YES] forKey:(NSString *)kCTUnderlineStyleAttributeName];

messageLabel.dataDetectorTypes = UIDataDetectorTypeLink;

messageLabel.userInteractionEnabled = YES;

I have implemented the delegate method like this:
- (void)attributedLabel:(TTTAttributedLabel *)label didSelectLinkWithURL:(NSURL *)url {
  NSLog(@"links on uilabel work");
  }

Also there are no gesture recognizers on the view.

**Comment by cbowns** [comment]
@alexito4 thanks for reporting this and writing your test project. this answers a question i'm having around TTTAttributedLabel tap handling with a button underneath it. (the reason for that nonsense is… complicated.)
