### ISSUE TITLE
Links with line break breaks the ParagraphStyle.

### ISSUE THREAD

**Issue by blommegard** [TTTAttributedLabel/TTTAttributedLabel#295]
When having links that wraps over a line break, the layout (ParagraphStyle) ends up very weird as shown in the picture below.

![untitled](https://f.cloud.github.com/assets/86447/1793207/5a56064c-69ae-11e3-8313-e40df1d9ff42.png)

Just to be clear, the middle image doesn't have a link what so ever and the top one got it on "ons and ".
It ends up the same way if the link start on "User…" as well.

Haven't had the time to dig in to it just yet, if someone can point me in a direction that would be great.

**Comment by mordani** [comment]
I still see this issue in 2.0.0 version. I set the line break (of a paragraph style) of the linkAttribute to NSLineBreakByWorkdWrapping but that doesnt seem to help in any way :(
