### ISSUE TITLE
drawTextInRect/adjustsFontSizeToFitWidth doesn't always use original string for re-calculating size 

### ISSUE THREAD

**Issue by ChrisLoer** [TTTAttributedLabel/TTTAttributedLabel#393]
If `drawTextInRect` adjusts the font size based on the `adjustsFontSizeToFitWidth` property, it saves off an `originalAttributedString` and restores the value after it's finished drawing the label. When it restores the value it explicitly avoids resetting the framesetter - I don't know enough to know why it needs to keep around the framesetter, but my guess is it's for performance or maybe for correctly calculating further calls to things like `instrinsicContentSize`? The problem occurs on subsequent calls to `drawTextInRect`: `sizeThatFits` passes `attributedText` (the original value) into `CTFramesetterSuggestFrameSizeForAttributedStringWithConstraints`, but the sizing is done based on the reduced-size string used by the current framesetter.

This showed up as problem for me because I had an animation that momentarily rendered a smaller version of my label before rendering the full size version. The font got scaled down for the initial small version, but never got scaled back to its original size for the full size version.

The workaround I'm using now is just to explicitly reset the framesetter every time `drawTextInRect` wants to calculate sizing information:

    // Adjust the font size to fit width, if necessarry
    if (self.adjustsFontSizeToFitWidth && self.numberOfLines > 0) {
        [self resetFramesetter]; // Framesetter could still be working with a resized version of the text, need to reset so we start from the original font size.
        // Use infinite width to find the max width, which will be compared to availableWidth if needed.
        CGSize maxSize = (self.numberOfLines > 1) ? CGSizeMake(TTTFLOAT_MAX, TTTFLOAT_MAX) : CGSizeZero;

        CGFloat textWidth = [self sizeThatFits:maxSize].width;

`resetFramesetter` is:

    - (void)resetFramesetter
    {
        [self setNeedsFramesetter];
        [self setNeedsDisplay];
        
    #if __IPHONE_OS_VERSION_MAX_ALLOWED >= 60000
        if ([self respondsToSelector:@selector(invalidateIntrinsicContentSize)]) {
            [self invalidateIntrinsicContentSize];
        }
    #endif
    }

**Comment by getaaron** [comment]
Thanks for the report, @ChrisLoer. Your suggested fix is now merged in.
