### ISSUE TITLE
sizeThatFits: broken on iOS 8?

### ISSUE THREAD

**Issue by koraktor** [TTTAttributedLabel/TTTAttributedLabel#402]
Can anyone confirm that `sizeThatFits:` is broken on iOS 8?

I have multiple labels that are sized incorrectly on iOS 8 (both too small and much too big in height). It seems like some sort of factor is involved: Single line labels are too small, while two or three line labels are correct, but anything with more lines will be bigger than necessary.

I'm using code similar to this (which works on iOS 6 and 7):

```objc
CGSize targetSize = CGSizeMake(someWidth, CGFLOAT_MAX);
CGSize labelSize = [someLabel sizeThatFits:targetSize];
```

**Comment by gimenete** [comment]
Any workaround to fix this? Thanks!

**Comment by jhersh** [comment]
If your label has a custom `attributedTruncationToken`, please do see latest `master` for a sizing fix that now takes the truncation token into account. 

Comments above are also fairly old at this point; has anyone a more specific reproducible case for this? The specific case of mixed language labels is covered elsewhere: #522

**Comment by rex-remind101** [comment]
I'm still seeing this issue on iOS 7.1. Using version `1.13.4`.
