### ISSUE TITLE
accessibilityElements' accessibilityFrame attribute are not set properly

### ISSUE THREAD

**Issue by cppcho** [TTTAttributedLabel/TTTAttributedLabel#458]
When a TTTAttributedLabel is placed on UIScrollView and use the VoiceOver function, the frames (accessibilityFrame) of the TTTAttributedLabel and the links inside are not correct. 

Btw I am using iOS8.

**Comment by cppcho** [comment]
Any comment on the above example? Thanks

**Comment by buddingmonkey** [comment]
Same issue is occurring on another project (that unfortunately we can't share), but wanted to pop in and say you're not the only one.
