### ISSUE TITLE
TTTAttributedLabel crashing in Xcode 6.1 (6A1052d)

### ISSUE THREAD

**Issue by troypayne** [TTTAttributedLabel/TTTAttributedLabel#462]
Under Release builds, my app is crashing whenever I tap a link in my TTTAttributedLabel.  This works with Release builds that were made 2 months ago... (not sure what Xcode that was) but now it crashes at:

[self.delegate attributedLabel:self didSelectLinkWithURL:result.URL];

using the URL:

let url = NSURL(string: "c0smo://profile/?guid=(pa.guid)&username=(pa.username)&aguid=(pa.aguid)")!

Whenever I use the basic url: http://www.google.com/ it doesn't crash.  I think it may be related to Swift and NSTextCheckingResult in some way.

The error is an EXEC_BAD_ACCESS (see attached screenshots)

Note, this does not crash under Debug builds

![screen shot 2014-12-01 at 12 59 20 am](https://cloud.githubusercontent.com/assets/3412692/5241882/8494a75e-78f5-11e4-8eda-e22aab7cdbec.png)
![screen shot 2014-12-01 at 1 00 41 am](https://cloud.githubusercontent.com/assets/3412692/5241883/8495e68c-78f5-11e4-9c23-a6f780abe1aa.png)

**Comment by robertoferraz** [comment]
@mattt I am having the same issue 
![screen shot 2015-03-20 at 14 15 24](https://cloud.githubusercontent.com/assets/270483/6752182/73760f2c-cf0c-11e4-87a3-64120b1266d9.png)

**Comment by jhersh** [comment]
@robertoferraz Your console shows that you're sending `setDelegate:` to an instance of `UILabel`. You are using a `UILabel` object instead of a `TTTAttributedLabel`. If you set up your UI in Interface Builder, ensure your label has the proper class.
