### ISSUE TITLE
Label cancels scrolling

### ISSUE THREAD

**Issue by Shagans982** [TTTAttributedLabel/TTTAttributedLabel#465]
I have a TTTAttributedLabel inside an iCarousel scrollview and it seems to be canceling scrolling when the touch point to scroll is onto of the label. UILabel works, Im not sure if there is a property I am missing that needs to be set? I am enabling link data detection but it occurs on when I haven't enabled links as well.

**Comment by Sh1mor1nka** [comment]
I have the same issue, when i scrolling i tap the screen to continue and my scrollview stop scrolling. May be it's because I use attributed string?

**Comment by lethianqt94** [comment]
@getaaron I tried to use it inside UIScrollView and also Autolayout but I failed. Can you give me an example?

**Comment by mhoeller-clue** [comment]
Not sure if this is still an issue for you guys. I ran into the same problem and found the root of it. iCarousel's pan gesture recognizer does not receive the touch  if the touched view implements `touchesMoved:withEvent:`, with exceptions for UIScrollView, UIButton and UIBarButtonItem. TTTAttributedLabel implements `touchesMoved:withEvent:` and thus iCarousel chooses not to pan and defers to the label. 
I don't have a solution for it. I guess some kind of configuration or a new delegate method on iCarousel would work.
