### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by MrReN** [TTTAttributedLabel/TTTAttributedLabel#483]
If AUITableView have a AUITableViewCell,and AUITableViewCell has a BUITableView, then the TTTAttributedLabel in BUITableViewCell,now ,if you scroll ,and drag stop,the BUITableView can't onclick,Why?

**Comment by getaaron** [comment]
Sounds like a problem with your view hierarchy. I can't think of anything in `TTTAttributedLabel` that would cause this.

If you think it's a bug in the library can you upload a sample project that reproduces the behavior?

**Comment by jhersh** [comment]
You have a label in a table cell in a tableview in a table cell in a tableview. It sounds like you have a very complex view hierarchy and you will need to ensure you are forwarding touches to the appropriate subview.
