### ISSUE TITLE
Is there a bug at setLinks: without retain then new array argument. my project crash at this point every time, and i fixed it by retain the argument.

### ISSUE THREAD

**Issue by troyzhao** [TTTAttributedLabel/TTTAttributedLabel#485]
replace
_links =  links;
with
if (_links != links) {
        [_links release];
        _links = [links retain];
    }

**Comment by jhersh** [comment]
@troyzhao TTTAttributedLabel requires ARC. If you are using TTTAttributedLabel in a project without ARC enabled, you should add `-fobjc-arc` to the compiler flags for `TTTAttributedLabel.m`.

**Comment by troyzhao** [comment]
OK, thanks
