### ISSUE TITLE
why search fail 

### ISSUE THREAD

**Issue by yin329039646** [TTTAttributedLabel/TTTAttributedLabel#487]
$ pod search TTTAttributedLabel
[!] Unable to find a pod with name matching `TTTAttributedLabel'

**Comment by jhersh** [comment]
`pod search` searches your local specs cache. Try running `pod setup` first to ensure your local repo is up to date.

**Comment by yin329039646** [comment]
i am using version 0.35.0,it's not latest ？

**Comment by jhersh** [comment]
CocoaPods 0.35 is the current release.

**Comment by yin329039646** [comment]
thinks ，The problem solved，I reinstall it
