### ISSUE TITLE
Why do I have to set text only after the font, line breaking are set up?

### ISSUE THREAD

**Issue by purrrminator** [TTTAttributedLabel/TTTAttributedLabel#488]
I spent hour to find the reason why lineBreakMode was not applied to my text.

```
TTTAttributedLabel *footerLabel = [TTTAttributedLabel new];
footerLabel.font = USERS_FOOTER_FONT;
footerLabel.text = USERS_FOOTER_TEXT;
footerLabel.delegate = self;
footerLabel.lineBreakMode = NSLineBreakByWordWrapping;
footerLabel.numberOfLines = 0;
```

found out that the text must be set only after the lineBreakMode is set. Didn't expect this unusual behaviour.

**Comment by jhersh** [comment]
Assuming your `USERS_FOOTER_TEXT` is a plain `NSString`, assigning to the `text` property will have the label construct an `NSAttributedString` based on the other text properties of the label. If you change label properties after the text has been assigned, the generated `NSAttributedString` remains the same and the label doesn't change. See this note in the comments of the `setText:` method:

> If the specified text is an `NSString`, the label will display the text like a `UILabel`, inheriting the text styles of the label.

So, you have two options:

- If you assign an `NSString` to the `text` property, you should do so after other label style properties have been assigned
- You can instead assign an `NSAttributedString` that includes the attributes you like, including line break mode, and it'll no longer matter in which order you assign to `text`.

**Comment by purrrminator** [comment]
Is there a chance to improve this part? I mean I'd like to re-generate the `NSAttributedString` each time any  attribute changed...

**Comment by jhersh** [comment]
Regenerating the attributed string and redrawing the label every time you change a text property would definitely add a lot of extra overhead. There's certainly room for improvement here. Hopefully the documentation is now clearer about this behavior.

**Comment by purrrminator** [comment]
Ok thanks
