### ISSUE TITLE
iOS 8 reuse in UICollectionViewCell, the linkAttributes dosen't work.

### ISSUE THREAD

**Issue by ZuYuanZhou** [TTTAttributedLabel/TTTAttributedLabel#489]
override func awakeFromNib() {
		super.awakeFromNib()
		self.contentLbl.delegate = self
		self.contentLbl.linkAttributes = [NSForegroundColorAttributeName : UIColor.rgb(hexRGB: "57B4FF")]
}

The first cell is OK. but the reused ones lost the link attributes

**Comment by jhersh** [comment]
@ZuYuanZhou Try `(id)kCTForegroundColorAttributeName`.

**Comment by ZuYuanZhou** [comment]
Use kCTForegroundColorAttributeName fix the issue, thanks!
