### ISSUE TITLE
Improvement: addLinkToTarget:action:withRange:

### ISSUE THREAD

**Issue by dkk** [TTTAttributedLabel/TTTAttributedLabel#490]
It would be very nice to have a method like 

```
      - (void)addLinkToTarget:(id)target action:(SEL)selector withRange:(NSRange)range
```

**Comment by jpcguy89** [comment]
I second this.

**Comment by getaaron** [comment]
Is this preferable over a block-based syntax?

**Comment by jhersh** [comment]
I think this is a fine addition. I'd be more keen on doing this with a block than with a target-selector pair. I'll look into it.

**Comment by jhersh** [comment]
Thoughts on #507?
