### ISSUE TITLE
feature request: NSTextAttachment

### ISSUE THREAD

**Issue by ghazel** [TTTAttributedLabel/TTTAttributedLabel#492]
As mentioned in #447, `TTTAttributedLabel` does not support `NSTextAttachment`. This was surprising, and undesirable.

This is a feature request for `NSTextAttachment` support.

**Comment by bteitelb** [comment]
+1

**Comment by sebleon** [comment]
+1

**Comment by blitzCA** [comment]
+1

**Comment by getaaron** [comment]
I've been thinking about moving all the drawing responsibility to `UILabel`, which would accomplish this. We'd have to drop support for pre-iOS 6, maybe pre-7 though.

**Comment by ghazel** [comment]
FWIW, I only support >= 7 anyway.

**Comment by Igor-Palaguta** [comment]
+1

**Comment by Igor-Palaguta** [comment]
Does anybody knows good workaround, how images can be embedded to uilabel?

**Comment by getaaron** [comment]
If anyone wants to collaborate, [the `drawing-with-uilabel` branch of my `TTTAttributedLabel` fork]( https://github.com/getaaron/TTTAttributedLabel/tree/drawing-with-uilabel) contains a rough, incomplete implementation of `TTTAttributedLabel`, dropping pre-iOS 7 support.

So far:

- It compiles
- The test app behaves mostly (but not entirely) the same
- I had to comment out most of the tests to get it to compile
- Some of the features being tested have been removed
- Some stuff has been deleted, other has been commented out
- All of the drawing code has been removed (so it draws identically to `UILabel` now)

I haven't had time to test it beyond this initial gutting, but I think you should now be able to embed text attachments like so:

```objc
NSTextAttachment *attachment = [[NSTextAttachment alloc] init];
attachment.image = [UIImage imageNamed:@"aaron-brager-avatar.png"];

NSAttributedString *attachmentString = [NSAttributedString attributedStringWithAttachment:attachment];

NSMutableAttributedString *myString= [[NSMutableAttributedString alloc] initWithString:@"Aaron Brager"];
[myString appendAttributedString:attachmentString];

myLabel.attributedText = myString;
```

**Comment by jhersh** [comment]
Very exciting @getaaron!

> dropping pre-iOS 7 support

That is unfortunate; iOS 4.3 support has long been a hallmark feature of TTTAttributedLabel. I'm not sure how we would measure deployments of the label on older systems, but I imagine it is still fairly popular. It'd be a real shame to lose this even though it'd also mean simpler drawing and much less code. Still, I imagine it's only a matter of time until one reason or another leads us to drop older systems.

> All of the drawing code has been removed (so it draws identically to UILabel now)

This also means that support for `highlightedShadowOffset`/`highlightedShadowRadius` et. al. have been removed, right? What of `verticalAlignment` and `textInsets` and any other features derived from the label's custom drawing?  Are the `NSAttributedString` character attributes adequate replacements for all of these?

This sounds like a fairly major change. We'll want to try for feature parity to the best extent we can, even if there are breaking syntax/property changes.

**Comment by getaaron** [comment]
@jhersh As you suspected, those features are all currently broken. Some of them can be trivially reimplemented, although I'm not sure they all need to be.

For those you mentioned:

- `textInsets` can now be [trivially configured with `NSParagraphStyle`](http://stackoverflow.com/a/21155606/1445366).
- `verticalAlignment` may no longer be necessary now that auto-layout and sizing work as they do on `UILabel`.
- I can't think of an easy alternative to `highlightedShadowOffset` and `highlightedShadowRadius`, but there may be similar text attributes which I'm missing. Alternatively, we could draw our own backgrounds and add them as subviews of the main view, but that's obviously a last resort.

**Comment by Igor-Palaguta** [comment]
My app uses >=iOS7, so easily switched to native UITextView. It supports links and images - all I need

**Comment by ocrickard** [comment]
It is possible to implement this using the current CoreText engine and not fork the implementation, right?  We would scan the incoming text with NSTextAttachmentAttributeName and embed a CTRunDelegateRef on the string for these regions that would allow us to leave space inline in the text.  In the drawing pass you get the attachment cell and request it draw within the region left.

**Comment by jhersh** [comment]
@ocrickard That does sound promising! I would welcome a pull request with those changes.

**Comment by ekrivopaltsev** [comment]
Folks, if NSTextAttachment with image supported in version 2.0.0 ?

**Comment by getaaron** [comment]
`NSTextAttachment` is still unsupported. I would happily review a PR adding it back in. Otherwise, I'll keep it on hold for a future version of TTTAttributedLabel.

**Comment by hytzxd** [comment]
+1

**Comment by holyen** [comment]
+1

**Comment by YuriyTrach** [comment]
+1

**Comment by iShawnWang** [comment]
+1

**Comment by xilin** [comment]
+1

**Comment by oded-regev** [comment]
+1

**Comment by shafqat-muneer** [comment]
Is `NSTextAttachment` now supported in `TTTAttributedLabel` or still not?

**Comment by lovisty** [comment]
NSTextAttachment is still unsupported, you can choose YYtext.
