### ISSUE TITLE
Link copy semantics not used

### ISSUE THREAD

**Issue by getaaron** [TTTAttributedLabel/TTTAttributedLabel#495]
https://github.com/TTTAttributedLabel/TTTAttributedLabel/commit/c84bb3b5172a3de6df490b80da0ef1155fc31b44 changed the link properties to use `copy`, but these objects will never be copied since they are `readonly` and https://github.com/TTTAttributedLabel/TTTAttributedLabel/commit/3b52d164e7b7f0735445060662c5709e26835571 directly assigns the objects passed to the initializer to the backing instance variables.

The initializer should either use property assignment (`self.attributes = attributes;`) or it should copy the objects (`_attributes = [attributes copy];`).

**Comment by jhersh** [comment]
You are correct! My mistake.
