### ISSUE TITLE
Touches ended on a link causes tableView:didSelectRowAtIndexPath: to fire

### ISSUE THREAD

**Issue by renssies** [TTTAttributedLabel/TTTAttributedLabel#499]
We are working on an app that closes the table cell (makes it smaller) when ```tableView:didSelectRowAtIndexPath:``` is called. However touches ended on a link in TTTAttributedLabel also still causes this to fire. 

I've done some random testing and if ```touchesMoved:withEvent:``` is called before ```touchesEnded:withEvent:``` with a link ``` tableView:didSelectRowAtIndexPath:``` is not fired.

**Edit:** The fix doesn't seem to work with the newest version of TTTAttributedLabel

**Comment by jhersh** [comment]
In the example `Espressos` project, tapping a link in any of the table cells does **not** call `tableView:didSelectRowAtIndexPath:`, which is as intended. I'm not sure I understand what you're expecting to happen here. Can you elaborate further?

Generally any time you have a custom or complex view hierarchy, you'll want to ensure you are forwarding touches as appropriate for your particular app.
