### ISSUE TITLE
TTTAttributedLabel in UITableViewCell with text lengh up 3000 characters

### ISSUE THREAD

**Issue by ItsTipTop** [TTTAttributedLabel/TTTAttributedLabel#503]
In my cell text length up 3000k symbols and scroll lag. 
I run my app with time profiler. characterIndexAtPoint function work very slow. 
Because of this, scrolling may hang on for 1-2 seconds, what can be done? 
![2015-02-18 14 32 39](https://cloud.githubusercontent.com/assets/1473763/6246541/41a13434-b77b-11e4-98ed-50968975a27d.png)

**Comment by getaaron** [comment]
Set `extendedLinkTouchArea` to `NO`. (And make sure you're on the newest version.)

**Comment by ItsTipTop** [comment]
It works. Thank you!
