### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by vishnurkaimal** [TTTAttributedLabel/TTTAttributedLabel#510]
I am using latest class, but build goes to fail.

../Attributed Label/TTTAttributedLabel.h:74:1: error: unknown type name
      'IB_DESIGNABLE'
IB_DESIGNABLE
^
../Attributed Label/TTTAttributedLabel.h:101:1: error: cannot combine with
      previous '(error)' declaration specifier
@interface TTTAttributedLabel : UILabel <TTTAttributedLabel, UIGestureRe...
^
../Attributed Label/TTTAttributedLabel.h:171:31: error: unknown type name
      'IBInspectable'
@property (nonatomic, assign) IBInspectable CGFloat shadowRadius;
                              ^
../Attributed Label/TTTAttributedLabel.h:171:52: error: expected ';' at end of
      declaration list
@property (nonatomic, assign) IBInspectable CGFloat shadowRadius;
                                                   ^
                                                   ;
../Attributed Label/TTTAttributedLabel.h:171:53: warning: type specifier
      missing, defaults to 'int' [-Wimplicit-int]
@property (nonatomic, assign) IBInspectable CGFloat shadowRadius;
                                                    ^~~~~~~~~~~~
../Attributed Label/TTTAttributedLabel.h:176:31: error: unknown type name
      'IBInspectable'
@property (nonatomic, assign) IBInspectable CGFloat highlightedShadowRadius;
                              ^
../Attributed Label/TTTAttributedLabel.h:176:45: error: property has a previous
      declaration
@property (nonatomic, assign) IBInspectable CGFloat highlightedShadowRadius;
                                            ^
../Attributed Label/TTTAttributedLabel.h:171:45: note: property declared here
@property (nonatomic, assign) IBInspectable CGFloat shadowRadius;
                                            ^
../Attributed Label/TTTAttributedLabel.h:176:52: error: expected ';' at end of
      declaration list
@property (nonatomic, assign) IBInspectable CGFloat highlightedShadowRadius;
                                                   ^
                                                   ;
../Attributed Label/TTTAttributedLabel.h:176:53: warning: type specifier
      missing, defaults to 'int' [-Wimplicit-int]
@property (nonatomic, assign) IBInspectable CGFloat highlightedShadowRadius;
                                                    ^~~~~~~~~~~~~~~~~~~~~~~
../Attributed Label/TTTAttributedLabel.h:180:31: error: unknown type name
      'IBInspectable'
@property (nonatomic, assign) IBInspectable CGSize highlightedShadowOffset;
                              ^
../Attributed Label/TTTAttributedLabel.h:180:51: error: expected ';' at end of
      declaration list
@property (nonatomic, assign) IBInspectable CGSize highlightedShadowOffset;
                                                  ^
                                                  ;
../Attributed Label/TTTAttributedLabel.h:180:52: warning: type specifier
      missing, defaults to 'int' [-Wimplicit-int]
@property (nonatomic, assign) IBInspectable CGSize highlightedShadowOffset;
                                                   ^~~~~~~~~~~~~~~~~~~~~~~
../Attributed Label/TTTAttributedLabel.h:184:31: error: unknown type name
      'IBInspectable'
@property (nonatomic, strong) IBInspectable UIColor *highlightedShadowColor;
                              ^
../Attributed Label/TTTAttributedLabel.h:184:1: error: property with
      'retain (or strong)' attribute must be of object type
@property (nonatomic, strong) IBInspectable UIColor *highlightedShadowColor;
^
../Attributed Label/TTTAttributedLabel.h:184:52: error: expected ';' at end of
      declaration list
@property (nonatomic, strong) IBInspectable UIColor *highlightedShadowColor;
                                                   ^
                                                   ;
../Attributed Label/TTTAttributedLabel.h:184:54: warning: type specifier
      missing, defaults to 'int' [-Wimplicit-int]
@property (nonatomic, strong) IBInspectable UIColor *highlightedShadowColor;
                                                    ~^
../Attributed Label/TTTAttributedLabel.h:189:31: error: unknown type name
      'IBInspectable'
@property (nonatomic, assign) IBInspectable CGFloat kern;
                              ^
../Attributed Label/TTTAttributedLabel.h:189:45: error: property has a previous
      declaration
@property (nonatomic, assign) IBInspectable CGFloat kern;
                                            ^
../Attributed Label/TTTAttributedLabel.h:171:45: note: property declared here
@property (nonatomic, assign) IBInspectable CGFloat shadowRadius;
                                            ^
../Attributed Label/TTTAttributedLabel.h:189:52: error: expected ';' at end of
      declaration list
@property (nonatomic, assign) IBInspectable CGFloat kern;
                                                   ^
                                                   ;
../Attributed Label/TTTAttributedLabel.h:189:53: warning: type specifier
      missing, defaults to 'int' [-Wimplicit-int]
@property (nonatomic, assign) IBInspectable CGFloat kern;
                                                    ^~~~
../Attributed Label/TTTAttributedLabel.h:198:31: error: unknown type name
      'IBInspectable'
@property (nonatomic, assign) IBInspectable CGFloat firstLineIndent;
                              ^
../Attributed Label/TTTAttributedLabel.h:198:45: error: property has a previous
      declaration
@property (nonatomic, assign) IBInspectable CGFloat firstLineIndent;
                                            ^
../Attributed Label/TTTAttributedLabel.h:171:45: note: property declared here
@property (nonatomic, assign) IBInspectable CGFloat shadowRadius;
                                            ^
../Attributed Label/TTTAttributedLabel.h:198:52: error: expected ';' at end of
      declaration list
@property (nonatomic, assign) IBInspectable CGFloat firstLineIndent;
                                                   ^
                                                   ;
../Attributed Label/TTTAttributedLabel.h:198:53: warning: type specifier
      missing, defaults to 'int' [-Wimplicit-int]
@property (nonatomic, assign) IBInspectable CGFloat firstLineIndent;
                                                    ^~~~~~~~~~~~~~~
../Attributed Label/TTTAttributedLabel.h:203:31: error: unknown type name
      'IBInspectable'
@property (nonatomic, assign) IBInspectable CGFloat leading DEPRECATED_A...
                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
6 warnings and 20 errors generated.

** ARCHIVE FAILED **

**Comment by jhersh** [comment]
@vishnurkaimal Perhaps you are using an old version of Xcode? `IBInspectable` and `IB_Designable` require Xcode 6.

**Comment by hsusmita** [comment]
I am using Xcode version 6.2. I am getting following errors:
 IB Designables: Failed to update auto layout status: Failed to load designables from path (null)
IB Designables: Failed to render instance of TTTAttributedLabel: Failed to load designables from path (null)

**Comment by jhersh** [comment]
@hsusmita You are probably using TTTAttributedLabel as a static library. See https://github.com/TTTAttributedLabel/TTTAttributedLabel/issues/460#issuecomment-70974996
