### ISSUE TITLE
setAttributedText not reseting links

### ISSUE THREAD

**Issue by Arrnas** [TTTAttributedLabel/TTTAttributedLabel#513]
I seem to have the same issue as #274. With the current version, using the label inside a tableview cell setAttributedText seems to reset the styling of the text since the text doesn't have link stylings, but the range is still clickable with the old link. 
I tried adding 
    
    self.linkModels = [NSArray array];

inside setAttributedString and it seems to remove the old links, but when a correct link is set it becomes unclickable after one click or long press.

**Comment by Arrnas** [comment]
I noticed that setText is able to take attributed strings. Using setText seems to resolve the problem of old links not being removed but introduces a different problem - it detects phone numbers in my attributed string despite not doing anything to enable this, is it possible to disable the checking? NSTextCheckingType doesn't seem to have a none option for enabledTextCheckingTypes.

**Comment by jhersh** [comment]
Also see this note in `TTTAttributedLabel.h`:

```
@warning Do not set this property directly. Instead, set @c text to an @c NSAttributedString.
```

As you've noted, you should instead call `setText:` with either a regular or attributed string.

**Comment by Arrnas** [comment]
I was already using attributed strings when i decided to drop in TTTAttributedLabel so I didn't see any warnings. I don't know how often setAttributedText is used but maybe it would be useful to add a deprecated warning on it. 
Anyways thanks for the reply and your work on this repo, it saved me a lot of time when i had to make my labels work with links.

**Comment by chikuba** [comment]
I just had the same issue, so yeah, a warning would be nice
