### ISSUE TITLE
How can I tap in hashtags rather than links?

### ISSUE THREAD

**Issue by Ricardo1980** [TTTAttributedLabel/TTTAttributedLabel#514]
Hello out there!

I see using something like
label.enabledTextCheckingTypes = NSTextCheckingTypeLink, label.delegate, addLinkToURL and didSelectLinkWithURL...
you can detect liinks and open them using a delegate (to open another view, or launch safari or show an action sheet)

I want something similar with hashtags like #helloworld

Do you have any recommendation to detect hashtags like #ThisIsAtag and that through the delegate open another view controller with that hashtags details?

Is it possible to use NSTextCheckingTypeRegularExpression?

I would appreciate any help. Thanks a lot in advance.

**Comment by jhersh** [comment]
`TTTAttributedLabel` does not currently support `NSTextCheckingTypeRegularExpression`. Pull requests welcome!

Instead, after you set the label's text, I would create an `NSRegularExpression` and loop through all hashtag matches in your label's text, adding a URL manually for each matching range. You could also iterate over regex matches in your string with `-[NSString rangeOfString:options:range]` and add a URL for each match.

**Comment by getaaron** [comment]
You should use Twitter's `twitter-text` objc library to detect hashtags. It will provide the correct `NSRange` for each hashtag.

**Comment by Ricardo1980** [comment]
Thanks!

@jhersh My question is, how can I execute a performSegue rather than opening a URL? Should I use a dummy URL like open://myhashtag

@getaaron I don't have ant problems detecting tags, actually I already paint them with a different color using attributedString, range and matches.

What I don't understand very well is how I can associate a piece of logic when a tag (or any other string) is pressed.

Any suggestion is welcome. Thanks.

**Comment by jhersh** [comment]
@Ricardo1980 you could use a dummy URL for which your app is a registered handler. Or, much more simply, just assign a block to the `TTTAttributedLabelLink` object you create for each hashtag. Or, if you don't like blocks, implement the delegate method for a text checking result being pressed.

**Comment by Ricardo1980** [comment]
Thanks for reply, I'm doing what @jhersh suggested me, using the delegate and a dummy url schema.
Very similar to this. 
http://stackoverflow.com/questions/20215965/tttattributedlabel-delegate-didselectlinkwithurl-is-not-getting-called-in-iphone

It works when I use tags like #thisisademo, the problem is that it fails when I use something like #dsaasdáds, that is, some letters with special marks. I see in touchesEnded, result.URL is nil. I guess the problem is related with letters and special marks that maybe are forbidden in a URL. Of course my tags use unicode and user should add that kind of letters.

Do you have any recommendation? Should I use didSelectLinkWithTextCheckingResult?
Thanks a lot.

**Comment by jhersh** [comment]
@Ricardo1980 I think it'd be much simpler to use a link tap block. See https://github.com/TTTAttributedLabel/TTTAttributedLabel/blob/master/TTTAttributedLabel/TTTAttributedLabel.h#L646-L658.

You can certainly use special marks in a URL; my guess is that your string is using an encoding that doesn't support them and so strips them out of your URL.

**Comment by Ricardo1980** [comment]
Thanks, it works.
I used:
            NSTextCheckingResult *result = [NSTextCheckingResult linkCheckingResultWithRange:match.range URL:nil];

and inside the block I capture my NSString. 
Don't know the reason why it works. But well, it works.
Thanks a lot.
