### ISSUE TITLE
Links are on highlighted/active state only briefly

### ISSUE THREAD

**Issue by ssfking** [TTTAttributedLabel/TTTAttributedLabel#515]
When I press and hold on to a link, the link would go to active/highlighted state for only a very short period of time (like 0.2s), before it returns to default/unhighlighted state. Did some debugging, seems like touchCancel is always called immediately after touchBegan on a link. Curious if anyone has also experienced this?

**Comment by ssfking** [comment]
Ok, so there is a LongPressGestureRecognizer that is being registered, and so everytime the longpressgesturerecognizer decides that it should receive touches, which is when there is a link sitting below it, it basically steals the touches away from the label itself, which results in the label being "touch canceled". I have to unregister the longpressgesturerecognizer or set "gestureRecognizer:shouldReceiveTouch:" to NO for the expected "button-like" behavior of the links to return.

**Comment by getaaron** [comment]
You can also disable `cancelsTouchesInView`.

**Comment by jhersh** [comment]
You can also disable the long press recognizer or just increase its `minimumPressDuration`.
