### ISSUE TITLE
kCTUnderlineStyleAttributeName style in iOS 8.1 Simulator

### ISSUE THREAD

**Issue by ParilShah** [TTTAttributedLabel/TTTAttributedLabel#516]
I have written below code for setting link Attributes, 
termsAndPrivacy.linkAttributes = @{ (id)kCTUnderlineStyleAttributeName: [NSNumber numberWithInt:NSUnderlineStyleSingle],
(id)kCTForegroundColorAttributeName: [UIColor lightGrayColor] };

Strange!! it works perfect in iOS 7, but in iOS 8 it takes Thick lines though I have set Underline Style as a single. For reference, see attached screenshot, refer RED block, it is designed with TTTAttributedLabel.
![tttattributedlabel](https://cloud.githubusercontent.com/assets/3435334/7032843/29fa5c64-dd93-11e4-9274-7e9aae8f742b.png)

**Comment by jhersh** [comment]
TTTAttributedLabel is expecting a boolean for that parameter; you should instead use something like `(id) kCTUnderlineStyleAttributeName : @YES` as the other underline styles are not supported.

You might also want to peek at `CTFontGetUnderlineThickness`, which TTTAttributedLabel uses to determine the underline thickness. Different fonts have different underline thicknesses, and it seems there may be some other rendering differences between iOS 7 and 8.

**Comment by ParilShah** [comment]
Thanks for your comment. Yes, I am using custom font family, Cabin. After your comment, I have made changes in Font and it works. :)
