### ISSUE TITLE
Bug when adding link to truncation attributed string

### ISSUE THREAD

**Issue by avnerbarr** [TTTAttributedLabel/TTTAttributedLabel#519]
The link attributed isn't added to the attributed truncation token correctly.

```objective-c
- (void)viewDidLoad {
    [super viewDidLoad];
    
    NSString *text = @"The NSString class declares the programmatic interface for an object that manages immutable strings. An immutable string is a text string that is defined when it is created and subsequently cannot be changed. NSString is implemented to represent an array of Unicode characters, in other words, a text string.";
    for (int i = 0; i < 10; i++) {
        TTTAttributedLabel *l1 = [[TTTAttributedLabel alloc] initWithFrame:CGRectMake(10, 10*(i+1) + (i * 50) + 10, self.view.bounds.size.width - (i +1)*20, 50)];
        l1.delegate = self;
        l1.userInteractionEnabled = YES;
        l1.numberOfLines = 2;
        l1.attributedTruncationToken = [[NSAttributedString alloc] initWithString:@"...more" attributes:@{NSForegroundColorAttributeName : [UIColor blueColor],
                                                                                                          NSLinkAttributeName : [NSURL URLWithString:@"http://more.com"]}];
//        l1.backgroundColor = [UIColor redColor];
        l1.text = text;
        [self.view addSubview:l1];
        l1.layer.borderColor = [UIColor redColor].CGColor;
        l1.layer.borderWidth = 2;
    }

}
- (void)attributedLabel:(TTTAttributedLabel *)label
   didSelectLinkWithURL:(NSURL *)url {
    NSLog(@"Here");
}
```

Notice that the link underlines are also not placed in the correct locations

![screen shot 2015-04-13 at 3 20 40 pm](https://cloud.githubusercontent.com/assets/2404795/7115359/b084fd78-e1f0-11e4-8db7-4afad264143c.png)

**Comment by jhersh** [comment]
Ahoy @avnerbarr, I've just added [some additional truncation token tests](https://github.com/TTTAttributedLabel/TTTAttributedLabel/commit/534b6b21ee2450c4a6f2467bbdf667246ab27ffe) to try and verify this behavior. It looks correct to me from what I can tell, both in those tests and in your screenshot. 

The attributed truncation links in your screenshot don't have an underline. Have you tried adding one with `NSUnderlineStyleAttributeName`? What specifically are you expecting to see here?

**Comment by knt** [comment]
I am having the exact same issue as @avnerbarr . When I try to set an attributed truncation token, an underline is getting added to earlier parts of my text that should not be there.

![Truncation Issue Example](https://dl.dropboxusercontent.com/u/341971/Screen%20Shot%202015-05-28%20at%205.35.43%20PM.png)

The blue color and underline in "ortor" on the second line should not be there...same for "attis" right before the [more] link.

```
_textLabel = [[TTTAttributedLabel alloc] initWithFrame:CGRectZero];
_textLabel.attributedTruncationToken = [[NSAttributedString alloc] initWithString:@"[more]"
                                                                attributes:@{ NSFontAttributeName : [UIFont boldSystemFontOfSize:12], NSForegroundColorAttributeName : [UIColor blueColor],                                                                              NSLinkAttributeName : [NSURL URLWithString:@"http://test.com"] }];
```

I'm sizing my label later.

**Comment by jhersh** [comment]
Thanks @knt for the extra detail, very helpful. I am on vacation now but I'll try to peek at this next week. PRs always welcome :)

**Comment by knt** [comment]
Thanks! I will try to dig in in the mean time.

**Comment by jhersh** [comment]
I'm still unable to reproduce this behavior. The label's attributed truncation token tests are using tokens much like the examples from @knt and @avnerbarr:

```objc
label.attributedTruncationToken = [[NSAttributedString alloc] initWithString:@"[more]"
                                                                      attributes:@{ NSFontAttributeName : [UIFont boldSystemFontOfSize:12],
                                                                                    NSForegroundColorAttributeName : [UIColor blueColor],
                                                                                    NSLinkAttributeName : [NSURL URLWithString:@"http://ytmnd.com"] }];
```

I've also tried adjusting `numberOfLines` to no avail. What am I missing here? Can you share any more code?

**Comment by knt** [comment]
Some additional details:
- I usually see this issue when I set the initial frame of the label to CGRectZero and then size the label later
- One issue I noticed is that when I set initial frame to be CGRectZero AND set custom lineSpacing, the textRect in textRectForBounds:limitedToNumberOfLines is not correctly calculated as it ignores the lineSpacing and just uses the font's default line height.This results in a smaller bounding box than the actual, and then the link/underline gets applied to the wrong line of text. With 3 lines of text, it would apply the underline to the 2nd line. I removed setting the lineSpacing, and while this fixed the issue on the second line of text, I still saw the underline in the wrong place on the last line of text

- I have a possible fix for the underline being misplaced when on the last line of text, but I need to do a bit more testing before submitting a PR

**Comment by jhersh** [comment]
Here's my current test, which uses both `CGRectZero` and a custom `lineSpacing`.

```objc
label = [[TTTAttributedLabel alloc] initWithFrame:CGRectZero];
label.numberOfLines = 3;
label.lineSpacing = 1.f;
label.attributedTruncationToken = [[NSAttributedString alloc] initWithString:@"[more]"
                                                                      attributes:@{ NSFontAttributeName : [UIFont boldSystemFontOfSize:12],
                                                                                    NSForegroundColorAttributeName : [UIColor blueColor],
                                                                                    NSLinkAttributeName : [NSURL URLWithString:@"http://ytmnd.com"] }];
label.text = TTTAttributedTestString();
[label setFrame:CGRectMake(0, 0, 120, 60)];
FBSnapshotVerifyView(label, nil);
```

There are no stray underlines; the label looks correct to me. :/

**Comment by avnerbarr** [comment]
You can run my attached code and it should reproduce the issue

**Comment by jhersh** [comment]
Alas, negative. I wrote this test based on your sample code:

```objc
- (void)testAttributedTruncation {
    label.userInteractionEnabled = YES;
    label.numberOfLines = 2;
    label.attributedTruncationToken = [[NSAttributedString alloc] initWithString:@"...more" attributes:@{NSForegroundColorAttributeName : [UIColor blueColor],
                                                                                                      NSLinkAttributeName : [NSURL URLWithString:@"http://more.com"]}];
    label.text = kTestLabelText;
    label.layer.borderColor = [UIColor redColor].CGColor;
    label.layer.borderWidth = 2;
    [label setFrame:CGRectMake(0, 0, 150, 45)];
    
    FBSnapshotVerifyView(label, nil);
}
```

Result:

![testattributedtruncation 2x](https://cloud.githubusercontent.com/assets/175139/7945509/1831c634-0926-11e5-8d10-09c83df2e0a3.png)

**Comment by jhersh** [comment]
I've added [your sample code](https://github.com/TTTAttributedLabel/TTTAttributedLabel/commit/0d014ab02acfe39018c50e63c347aa51587da04e) almost verbatim as a snapshot test, but it still doesn't demonstrate the issue. Let's revisit this if we can find a reproducible case.

**Comment by SquaredTiki** [comment]
Seeing this my self too, thought I'd add to this with my experience of the bug. If you increase the height so that the text where the truncation attributed string was shown is now visible then that text now has the color of a link attribute (although not the actual link attribute). You can see this when looking at the description of the attributed text also. Initially immediately after setting it is:

	Some text goes here that will be truncated{
	    CTForegroundColor = "UIDeviceRGBColorSpace 0.150563 0.150559 0.150561 1";
	    NSFont = "<UICTFont: 0x7a7ca300> font-family: \"Helvetica Neue\"; font-weight: normal; font-style: normal; font-size: 12.00pt";
	    NSKern = 0;
	    NSParagraphStyle = "Alignment 0, LineSpacing 3, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 13.98/13.98, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (null), Lists (null), BaseWritingDirection -1, HyphenationFactor 0, TighteningFactor 0, HeaderLevel 0";
	}

But afterwards, say when the link is tapped and handled within `attributedLabel:didSelectLinkWithURL` the attributed text is as follows:

	<p>Some text goes here that will b{
	    CTForegroundColor = "UIDeviceRGBColorSpace 0.150563 0.150559 0.150561 1";
	    NSFont = "<UICTFont: 0x7a7ca300> font-family: \"Helvetica Neue\"; font-weight: normal; font-style: normal; font-size: 12.00pt";
	    NSKern = 0;
	    NSParagraphStyle = "Alignment 0, LineSpacing 3, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 13.98/13.98, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (null), Lists (null), BaseWritingDirection -1, HyphenationFactor 0, TighteningFactor 0, HeaderLevel 0";
	}e tru{
	    CTForegroundColor = "UIDeviceRGBColorSpace 0 0 1 1";
	    NSFont = "<UICTFont: 0x7a7ca300> font-family: \"Helvetica Neue\"; font-weight: normal; font-style: normal; font-size: 12.00pt";
	    NSKern = 0;
	    NSParagraphStyle = "Alignment 0, LineSpacing 3, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 13.98/13.98, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (null), Lists (null), BaseWritingDirection -1, HyphenationFactor 0, TighteningFactor 0, HeaderLevel 0";
	    NSUnderline = 1;
	}ncated{
	    CTForegroundColor = "UIDeviceRGBColorSpace 0.150563 0.150559 0.150561 1";
	    NSFont = "<UICTFont: 0x7a7ca300> font-family: \"Helvetica Neue\"; font-weight: normal; font-style: normal; font-size: 12.00pt";
	    NSKern = 0;
	    NSParagraphStyle = "Alignment 0, LineSpacing 3, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 13.98/13.98, LineHeightMultiple 1, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (null), Lists (null), BaseWritingDirection -1, HyphenationFactor 0, TighteningFactor 0, HeaderLevel 0";
	}

Notice that the text in the range where the '…more' truncation attributed text would be shown ('e tru') has a forgeground color of pure blue and is underlined.

**Comment by ygweric** [comment]
@jhersh I know how to reproduce the bug, **Just tap the `...More`, the blue text will appear**

**Comment by ygweric** [comment]
I fix it, add  on line code at line 870, I will make a pull request later, maybe I need to change the unit test code later.

```
truncationString = [truncationString attributedSubstringFromRange:NSMakeRange(0, truncationString.length - attributedTruncationString.length)];
                [truncationString appendAttributedString:attributedTruncationString];//ADD THIS LINE
                CTLineRef truncationLine = CTLineCreateWithAttributedString((__bridge CFAttributedStringRef)truncationString);



```

**Comment by Gurpartap** [comment]
I had similar weirdness with a very simple `attributedTruncationToken`. When tapping the more link, it would highlight a few letters from the text instead, and sometimes it wouldn't let me tap on the last few letters of "more".

@ygweric's suggestion fixes it for me. ✨

**Comment by shaikshabana** [comment]
I still get this issue with attributedTruncationToken,can anybody help me to resolve this 
![simulator screen shot dec 12 2016 12 02 09 pm](https://cloud.githubusercontent.com/assets/5372732/21090017/dd2c1d5a-c062-11e6-8ce8-5e17f3010c81.png)

**Comment by stelalae** [comment]
me too

**Comment by stelalae** [comment]
@shaikshabana  I known, you must reset TTTAttributedLabel, eg.
`  _labelContent.text = nil;
    _labelContent.linkAttributes = nil;
    _labelContent.attributedText = nil;
    _labelContent.attributedTruncationToken = nil;`

**Comment by evayuhz** [comment]
> I fix it, add on line code at line 870, I will make a pull request later, maybe I need to change the unit test code later.
> 
> ```
> truncationString = [truncationString attributedSubstringFromRange:NSMakeRange(0, truncationString.length - attributedTruncationString.length)];//ADD THIS LINE
> [truncationString appendAttributedString:attributedTruncationString];
> CTLineRef truncationLine = CTLineCreateWithAttributedString((__bridge CFAttributedStringRef)truncationString);
> ```

Have you ever make a pull request for this? I didn't find this line in latest version.

**Comment by cclaflin89** [comment]
I have the same issue

**Comment by mendaparadarshit** [comment]
Hello Guys,

Please use this code to resolve this issue:
https://github.com/mendaparadarshit/TTTAttributedLabel

I have fixed in my repository and its working fine

Thanks

**Comment by mendaparadarshit** [comment]
> I have the same issue. Note that it looked fine on the first load, but the blue underlined string appears after tapping "Read More". I didn't set any other attributes except this truncationToken in this test.
> 
> Here are the test cases I've tried:
> 
> * didn't use auto layout
> * used auto layout
> * placed the label inside the cell
>   Experiencing the same issue for all 3 cases above.
> 
> `let attributedString = NSAttributedString(string: "...Read More", attributes: [NSAttributedString.Key.foregroundColor : UIColor.red, NSAttributedString.Key.link: NSURL(string: "https://google.com")!])
> 
> label.attributedTruncationToken = attributedString`
> 
> ![image](https://user-images.githubusercontent.com/39384394/59576563-8baa0d00-907d-11e9-8e0a-cde940de984b.png)
> 
> TTTAttributedLabel version 2.0.0

Solved this issue:https://github.com/TTTAttributedLabel/TTTAttributedLabel/issues/519#issuecomment-752873366

**Comment by karosLi** [comment]
I fixed it with following code in 811 line.

```
[truncationString appendAttributedString:attributedTruncationString];
                
// fix issue: truncation string is not incorrect range https://github.com/TTTAttributedLabel/TTTAttributedLabel/issues/519
NSMutableAttributedString *attributedText = [self.attributedText mutableCopy];
[attributedText appendAttributedString:attributedTruncationString];
self.attributedText = [attributedText copy];
lastLineRange = CFRangeMake(lastLineRange.location, lastLineRange.length + attributedTruncationString.length);

CTLineRef truncationLine = CTLineCreateWithAttributedString((__bridge CFAttributedStringRef)truncationString);
```

**Comment by ammadakh** [comment]
> I fixed it with following code in 811 line.
> 
> ```
> [truncationString appendAttributedString:attributedTruncationString];
>                 
> // fix issue: truncation string is not incorrect range https://github.com/TTTAttributedLabel/TTTAttributedLabel/issues/519
> NSMutableAttributedString *attributedText = [self.attributedText mutableCopy];
> [attributedText appendAttributedString:attributedTruncationString];
> self.attributedText = [attributedText copy];
> lastLineRange = CFRangeMake(lastLineRange.location, lastLineRange.length + attributedTruncationString.length);
> 
> CTLineRef truncationLine = CTLineCreateWithAttributedString((__bridge CFAttributedStringRef)truncationString);
> ```

@karosLi your code sometimes work sometimes doesn't, in your own commit you have a different code than what you mentioned in the thread. did you get it to working perfectly?
