### ISSUE TITLE
Reference from xib to TTTAttributedLabel - Xcode 6.3

### ISSUE THREAD

**Issue by m00sey** [TTTAttributedLabel/TTTAttributedLabel#520]
I had a TTTAttributedLabel as the custom class of a component in a xib used inside a UICollectionViewCell, after updating to Xcode 6.3 I got this error:

IB Designables: Failed to update auto layout status: Failed to load designables from path (null)

It referenced the TTTAttributedLabel in Xcode, sadly this manifests itself as xcode just hanging.

**Comment by jhersh** [comment]
This is not really a problem with TTTAttributedLabel; it's an issue with static libraries. See #460.

**Comment by m00sey** [comment]
Thanks for the heads up, it's manifestation (for me) is worse in 6.3 than described in #460, as in it killed Xcode.

Closing.
