### ISSUE TITLE
Phone number highlight incorrect if text contains the string 'phone'

### ISSUE THREAD

**Issue by jasonblood** [TTTAttributedLabel/TTTAttributedLabel#521]
I have noticed a issue with the phone number detection not working correctly when the labels text contains the string 'phone' in it. Here is a screenshot. 
![screen shot 2015-04-15 at 15 49 11](https://cloud.githubusercontent.com/assets/2226303/7161342/8d731b70-e386-11e4-842f-96e142313032.png)

If you look at the second and third cell you can see what I mean. Some of the text has been highlighted from the word 'Phone'. Had a quick look at the source and this project uses a NSDataDetector to pull out the links. So maybe its a bug with this apple api. (Also seems to be only happening since iOS 7) and couldn't find anything about this in the NSDataDetector docs.

**Comment by jhersh** [comment]
Can you share some of your code? Generally you'll want to make sure you are assigning to the `text` property after most other properties have been set, particularly your data detector type.

**Comment by jhersh** [comment]
@jasonblood If the word "phone" were involved here, I would expect to see the same issue in your fourth cell, right? I think it's more likely there is a table cell reuse problem.

**Comment by jasonblood** [comment]
hi @jhersh sorry about the slow reply (didn't get a notification about a response). I will try and get a sample project with this happening when I get some time.
But this is roughly how the label is set up in the cell ```

        _messageLabel = [[TTTAttributedLabel alloc] initWithFrame:CGRectZero];
        _messageLabel.textColor = CONTENT_TEXTCOLOR_LIGHT;
        _messageLabel.backgroundColor = [UIColor clearColor];
        _messageLabel.numberOfLines = 0;
        _messageLabel.enabledTextCheckingTypes = NSTextCheckingTypeLink | NSTextCheckingTypePhoneNumber; ```

And then the text is set on the label using the text property. So I hooked up the debugger and set a breakpoint here https://github.com/TTTAttributedLabel/TTTAttributedLabel/blob/master/TTTAttributedLabel/TTTAttributedLabel.m#L1125 and the data detector seems to parse the phone part out sometimes. So I guess this is an Apple bug
