### ISSUE TITLE
Setting text with same string (but possibly different styles) leads to a brief flicker for links added using enabledTextCheckingTypes

### ISSUE THREAD

**Issue by sophaz** [TTTAttributedLabel/TTTAttributedLabel#525]
On TTTAttributedLabel.m:975, the string is thrown to a global queue to find the search hits. This asynchronous call is the reason the flicker happens. Do we really get that much performance benefits for doing this?

**Comment by jhersh** [comment]
`NSDataDetector` can take some time to match multiple text checking types and return `NSTextCheckingResult` objects, particularly on longer text labels or with multiple labels. We definitely don't want to block the main thread while this is happening. Perhaps in your case, if the text is the same and the styles have not changed, you might avoid calling `setText:`?
