### ISSUE TITLE
How to calculate height when the label contain custom emoji?

### ISSUE THREAD

**Issue by passol1988** [TTTAttributedLabel/TTTAttributedLabel#530]
I failed to calculate height when the label contain custom emoji using TTTAttributedLabel?

**Comment by jhersh** [comment]
First make sure you are using the label's built-in sizing method, [`+[TTTAttributedLabel sizeThatFitsAttributedString:withConstraints:limitedToNumberOfLines:]`](https://github.com/TTTAttributedLabel/TTTAttributedLabel/blob/master/TTTAttributedLabel/TTTAttributedLabel.h#L286-L288). There are some known issues sizing text that contains emoji; see e.g. #405.

**Comment by thuai** [comment]
+1
