### ISSUE TITLE
how can i remove a link?

### ISSUE THREAD

**Issue by GreatFireWall** [TTTAttributedLabel/TTTAttributedLabel#531]

**Comment by jhersh** [comment]
Probably best to reassign to the label's `text` property and then skip adding a link to the range of text you wanted to remove.

**Comment by jhersh** [comment]
Please see [the `tttattributedlabel` tag on SO](http://stackoverflow.com/questions/tagged/tttattributedlabel) if you have other questions; this is not a support forum.
