### ISSUE TITLE
Link's slow down scrolling

### ISSUE THREAD

**Issue by andrewbradnan** [TTTAttributedLabel/TTTAttributedLabel#536]
When I have a TTTAttributedLabel with a lot of text and some links the control just dies during scrolling.  While dragging your finger just pauses badly, and once you let go it scrolls just fine.  So drawing seems to be no problem.

Instead of capturing all the touches (and doing all that hit testing), wouldn't you be better off just using a TapRecognizer?  You should only have to hit test once, not a million times.

Does that seem like a reasonable change to try?  Thanks.

**Comment by jhersh** [comment]
That (admittedly slow) hit-testing logic attempts to reproduce Safari's fuzzy extended touch areas for links. You might try disabling `extendsLinkTouchArea` when the user starts scrolling and re-enabling it after.

**Comment by etayluz** [comment]
Would just like to confirm that setting extendsLinkTouchArea to NO improves performance dramatically.

**Comment by andrewbradnan** [comment]
Indeed, much faster.
