### ISSUE TITLE
Warning Issues on Xcode 7 (iOS 9)

### ISSUE THREAD

**Issue by hightech** [TTTAttributedLabel/TTTAttributedLabel#538]
I am trying to figure out how to fix this issue in Swift project with -Bridging-Header I saw warnings on Xcode 7 (iOS9):

First Part:
![screen shot 2015-06-18 at 11 02 31 am](https://cloud.githubusercontent.com/assets/314631/8235840/fbb80852-15a9-11e5-898c-6fd5a9c37c02.png)

Second Part:
![screen shot 2015-06-18 at 11 02 11 am](https://cloud.githubusercontent.com/assets/314631/8235855/1449239c-15aa-11e5-9781-64665a392c27.png)

How can I fix it? Any suggestion appreciated. Thanks.

**Comment by jhersh** [comment]
These are just warnings for properties that have been deprecated starting in iOS 9. They are only warnings and there's really no action you need to take.

**Comment by jhersh** [comment]
In the longer term we'll need to modernize the label to account for updated or replaced Core Text constants.

**Comment by hightech** [comment]
Ok thanks!
