### ISSUE TITLE
Regression in firstLineHeadIndent

### ISSUE THREAD

**Issue by coverback** [TTTAttributedLabel/TTTAttributedLabel#540]
Hi!

Release 1.13.4 introduced regression and is not respecting `firstLineHeadIndent` in `NSParagraphStyle` anymore.

Commit that introduced the regression is 1b96484ea1d272b4bab27c6d3319941b708d36bd, "Fixed line drawing xOffset for multiple lines." in #528 

This is already a second time such a regression happens, last time it was fixed in #407. 

Snippet showing the issue:

    NSMutableParagraphStyle *style = [[NSParagraphStyle defaultParagraphStyle] mutableCopy];
    [style setFirstLineHeadIndent:20.0];

    NSDictionary *attr = @{NSParagraphStyleAttributeName: style};

    [self.tttLabel setAttributedText:[[NSAttributedString alloc] initWithString:@"TTTLabel" attributes:attr]];
    [self.uiLabel setAttributedText:[[NSAttributedString alloc] initWithString:@"UILabel" attributes:attr]];

[Small project showing the issue](https://dl.dropboxusercontent.com/u/69089444/TestTTTSize_indent.zip) and screenshot with TTT and UILabel next to each other:

![ttt_indent](https://cloud.githubusercontent.com/assets/481966/8251940/b4159cc2-1689-11e5-9b95-1b213826f29d.png)

**Comment by jhersh** [comment]
Hm, perhaps you have seen #494? Have you tried using the dedicated `firstLineIndent` property on the label for this?
