### ISSUE TITLE
attributedTruncationToken link crashes

### ISSUE THREAD

**Issue by linhj07** [TTTAttributedLabel/TTTAttributedLabel#541]
(the latest commit:[Truncation] Corrected token link range (fixes #537) #518 #519) the attributedTruncationToken with link calls app to crash on iphone 6, os8.1 for specific text and truncation settings.
crashes at:
[mutableAttributedString addAttributes:link.attributes range:link.result.range];
in line 580. with exception:
NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds (null)

---------------------------------------------------
For the text: 
SDA博科尼商学院（SDA Bocconi School of Management）成立于1971年。作为博科尼大学的一部分，学院在意大利处于领先地位，并拥有超过30年的MBA教学经验。SDA学院以深入研究、专业教严队伍、紧密结合商业圈而享誉国际。SDA博科尼为自身与商业世界的良好互动而自豪。

with these settings:
    NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
    paragraphStyle.lineBreakMode = NSLineBreakByWordWrapping;
    paragraphStyle.alignment = NSTextAlignmentJustified;
    
    NSAttributedString *attributedStr = [[NSAttributedString alloc] initWithString:content attributes:[NSDictionary dictionaryWithObjectsAndKeys:
                                                                                                 paragraphStyle,
                                                                                                 NSParagraphStyleAttributeName,
                                                                                                 [UIFont systemFontOfSize:kSystemFontSize],
                                                                                                 NSFontAttributeName,
                                                                                                 [UIColor redColor],                            NSForegroundColorAttributeName,nil
                                                                                                 ]];
    label.text = attributedStr;
    label.attributedTruncationToken = [[NSAttributedString alloc] initWithString:@"...查看全文"
                                    attributes:@{ NSFontAttributeName : [UIFont systemFontOfSize:16.0f],
                                                  NSForegroundColorAttributeName : [UIColor blueColor],
                                                  NSLinkAttributeName : [NSURL URLWithString:@"fulltext"],
                                                  NSUnderlineStyleAttributeName : @NO }];
    label.numberOfLines = 6;
    CGSize constraint = CGSizeMake(SCREEN_WIDTH-50, 20000.0f);
    CGRect rect = [attributedStr boundingRectWithSize:constraint options:NSStringDrawingUsesFontLeading | NSStringDrawingUsesLineFragmentOrigin context:nil];
    
    [label setFrame:CGRectMake(25,10,SCREEN_WIDTH-50,rect.size.height)];
    [label sizeToFit];

**Comment by jhersh** [comment]
`NSLinkAttributeName` must contain an `NSURL`, and we know that it has a failable initializer that may return nil for your example: `[NSURL URLWithString:@"fulltext"]`. Have you tried using a real full URL?

**Comment by linhj07** [comment]
@jhersh yes I have tried a real full url, but got the same crash with the above text and settings. With other text and the same settings, either a full url or the "fulltext" works just correct. But with the above text, it crashes

**Comment by jhersh** [comment]
Okay, let's revert for now. Clearly not quite fully baked just yet.

**Comment by linhj07** [comment]
I have also tried to remive link attribute in the attributedtruncationtoken and it works fine. So I guess the crash might be related to the link ranges caculation, thought I didnt go deep into the source code

**Comment by SquaredTiki** [comment]
In f243cc5 should it not be `(lastLineRange.location+tokenRange.location)` rather than `(lastLineRange.location+lastLineRange.length)`?

**Comment by joshuafeldman** [comment]
I am still seeing this crash. This ticket should probably be reopened
