### ISSUE TITLE
issue On link tap changes the color of all links TTTAttributedLabel

### ISSUE THREAD

**Issue by dhanrajp4u** [TTTAttributedLabel/TTTAttributedLabel#542]
I am using TTTAttributedLabel for display user tag on table view cell. I have issue when user tap on link one of cell tag user its automatic changes the all cell link string text color to text color.
In simulator working fine but on device getting this effect
 Help me, if I am missing something.

 - (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    static NSString *CellIdentifier = @"tttDemo";
    
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier forIndexPath:indexPath];
    
    if (cell == nil) {
        cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:CellIdentifier];
        cell.accessoryType = UITableViewCellAccessoryNone;
    }
    NSString *str= @"@dj hello @dhanraj @pradeep nice @test @well @team yes @good";
    TTTAttributedLabel *summaryLabel =(TTTAttributedLabel *)[cell viewWithTag:55];
    summaryLabel.font = [UIFont systemFontOfSize:14];
    summaryLabel.textColor = [UIColor blackColor];
    summaryLabel.lineBreakMode = NSLineBreakByWordWrapping;
    summaryLabel.numberOfLines = 0;
    summaryLabel.linkAttributes =[NSDictionary dictionaryWithObjectsAndKeys:
                                  
                                  [UIColor blueColor],(__bridge NSString *)kCTForegroundColorAttributeName,
                                  
                                  //                                    (__bridge id)[[UIColor yellowColor] CGColor],(NSString *)kTTTBackgroundFillColorAttributeName,
                                  
                                  [NSNumber numberWithBool:NO],
                                  (__bridge NSString *)kCTUnderlineStyleAttributeName,
                                  
                                  [UIFont boldSystemFontOfSize:14],(__bridge NSString *) kCTFontAttributeName
                                  ,nil];
    summaryLabel.userInteractionEnabled = YES;
    summaryLabel.delegate=self;
    summaryLabel.text=str;
    self.isAccessibilityElement = NO;
    //For clickable @tagged UserName
    NSRegularExpression *regexp=UserNameRegularExpression();
    
    [regexp enumerateMatchesInString:summaryLabel.text options:0 range:NSMakeRange(0, str.length) usingBlock:^(NSTextCheckingResult *result, __unused NSMatchingFlags flags, __unused BOOL *stop) {
        
        ///NSLog(@"loc= %lu length=%lu",(unsigned long)result.range.location,(unsigned long)result.range.length);
        NSURL *url = [NSURL URLWithString:[NSString stringWithFormat:@"http://%@", [str substringWithRange:result.range]]];
        [summaryLabel addLinkToURL:url withRange:result.range];
        
    }
     ];
    
    summaryLabel.activeLinkAttributes=nil;
    
    return cell;
}

![img_2300](https://cloud.githubusercontent.com/assets/1658151/8351622/7785693c-1b4c-11e5-99a3-e8f21cdb4183.PNG)
![img_2301](https://cloud.githubusercontent.com/assets/1658151/8351623/77912088-1b4c-11e5-8444-2973359adf88.PNG)

**Comment by deville** [comment]
Getting the same issue when presenting `UIAlertControl`. At the same time, `UIAlertView` does not cause this. Is there any solution?

Normal state: 
![screen shot 2015-07-13 at 17 34 24](https://cloud.githubusercontent.com/assets/4421971/8653644/b689fa3e-2985-11e5-85c1-a44dfce58eab.png)

With `UIAlertControl`:
![screen shot 2015-07-13 at 17 34 11](https://cloud.githubusercontent.com/assets/4421971/8653682/f8fef46e-2985-11e5-9cd7-03096d36ed48.png)

**Comment by deville** [comment]
Never mind, setting font in `inactiveLinkAttributes` fixed the problem.
