### ISSUE TITLE
UITapGestureRecognizer make didSelectLinkWithURL method unworked

### ISSUE THREAD

**Issue by zscorpio** [TTTAttributedLabel/TTTAttributedLabel#550]
I add 
```
    UITapGestureRecognizer *tap = [[UITapGestureRecognizer alloc] initWithTarget:self
                                                                          action:@selector(p_tapOnTableView:)];
    [self.tableView addGestureRecognizer:tap];
```
then didSelectLinkWithURL did not work..

how can i fix it?

**Comment by getaaron** [comment]
You have to configure the gesture recognizer not to cancel the view's touches, or implement the relevant delegate methods to ensure the feature recognizer doesn't recognize when a link is tapped.

**Comment by zscorpio** [comment]
I will have a try ,thank you~

**Comment by zscorpio** [comment]
#pragma mark UIGestureRecognizerDelegate
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch{
        return NO;   
}


I tryed this ,but it seems not worked..

**Comment by happyliuzh** [comment]
do not use gesture . can try - (void)touchesEnded:(NSSet *)touches  withEvent:(UIEvent *)event

**Comment by zscorpio** [comment]
ok  thank you~~
