### ISSUE TITLE
Performance problems with enabledTextCheckingTypes and cells

### ISSUE THREAD

**Issue by mRs-** [TTTAttributedLabel/TTTAttributedLabel#551]
I encountered today a heavy performance problem with my `NSTextCheckingTypeLink` and cells in an `UIScrollView` equivalent.

The main Problem is the hitTest, it's to much to do on the main thread with the current implementation.
![screenshot 2015-07-06 15 49 49](https://cloud.githubusercontent.com/assets/736421/8523624/ac5eeb12-23f6-11e5-9c34-f4188dfb4f48.png)

To reproduce this bug just add complete links to the current example project and set `enableTextCheckingType`.

    self.summaryLabel.enabledTextCheckingTypes = NSTextCheckingTypeLink;

And add some links to the espressos.txt file

I would like to fix this problem and IMHO it would be the easiest way to cache the characterIndexAtPoint. But is this the easiest solution or do you have better ideas to fix this little nasty bug?

**Comment by jhersh** [comment]
You should try setting `extendsLinkTouchArea` to `NO`.

**Comment by getaaron** [comment]
@jhersh Given the performance impact, what do you think about making `extendsLinkTouchArea` default to `NO`?

**Comment by jhersh** [comment]
I think there's a strong case to change the default to `NO`. This has come up before and surely will again. :)

**Comment by mRs-** [comment]
But wouldn't it be better to just support the extendsLinkTouchArea and to fix this with a caching behavior? It would be awesome for the TTTAttributedLabel to support this. I am willed to write a fix for this if it's possible to cache some things in the hitTest method

**Comment by jhersh** [comment]
I would welcome a pull request along those lines.

**Comment by mRs-** [comment]
will there any problem if i cache the values?

**Comment by getaaron** [comment]
@mrs- I think you'll need to invalidate the cache on a bounds, link, or text change.

**Comment by simplysavage71-lab** [comment]
I'm completely list, big surprise, I donr understand which codes go where to undo yalls mess
