### ISSUE TITLE
How to get TTTAttributedLabel's height without autolayout.

### ISSUE THREAD

**Issue by MickeyHub** [TTTAttributedLabel/TTTAttributedLabel#554]

**Comment by jhersh** [comment]
Be sure to see the label's built-in sizing method, [`+[TTTAttributedLabel sizeThatFitsAttributedString:withConstraints:limitedToNumberOfLines:]`](https://github.com/TTTAttributedLabel/TTTAttributedLabel/blob/master/TTTAttributedLabel/TTTAttributedLabel.h#L286-L288)
