### ISSUE TITLE
Does TTTAttributedLabel support paragraph head indent?

### ISSUE THREAD

**Issue by cerupcat** [TTTAttributedLabel/TTTAttributedLabel#559]
I'm having a hard time figuring out if TTTAttributedLabel supports all the styling of NSParagraphStyle including headIndent. From what I can tell, it doesn't appear to. If I were to implement this, where would I start?

**Comment by jhersh** [comment]
Yes, see the dedicated `firstLineIndent` property. You may also enjoy #494 and #540.

**Comment by cerupcat** [comment]
Thanks @jhersh, I should of been more clear. From what I can see the firstLineIndent applies to the whole text rather than sub paragraphs within an attributed string. I'm currently using DTCoreText to format html, but using TTAttributedLabel for the label. DTCoreText create sub paragraphs with different indentation depending on the html (like an ordered list for example), but TTAttributedLabel doesn't seem to fully respect the indents from what I ca tell.

**Comment by jhersh** [comment]
That's correct. Anything specific to add here, or perhaps we might close this in favor of #494?

**Comment by cerupcat** [comment]
I'll move over there. :)
