### ISSUE TITLE
Paragraph Styles

### ISSUE THREAD

**Issue by jhersh** [TTTAttributedLabel/TTTAttributedLabel#561]
This issue tracks an enhancement to the label that would add support for `NSParagraphStyle` and `CTParagraphStyleSpecifier ` metrics. This issue supersedes #494 and #540. 

 - `top`: `kCTParagraphStyleSpecifierParagraphSpacingBefore`
 - `left`: `kCTParagraphStyleSpecifierHeadIndent`
 - `bottom`: `kCTParagraphStyleSpecifierParagraphSpacing`
 - `right`: `kCTParagraphStyleSpecifierTailIndent`

**Comment by dustinkeeton** [comment]
Is this enhancement still being worked on? I could really use `headIndent` support.

**Comment by kwketh** [comment]
@dustinkeeton See if #683 resolves it for you?
