### ISSUE TITLE
Ability to select and copy text

### ISSUE THREAD

**Issue by kikin81** [TTTAttributedLabel/TTTAttributedLabel#578]
Is it possible to add the native iOS ability to select and copy text?
I understand that there is a UITextView that has this ability but was wondering if I could still use TTTAttributedLabel.

**Comment by getaaron** [comment]
You should be able to add a "Copy" menu using `UIMenuController` just like you would on a `UILabel`. Sample code here: http://nshipster.com/uimenucontroller/

You could also add the ability to copy by long-pressing a link. See "Responding to Long Presses" in the documentation.

Allowing the user to select specific letters or words is not supported and I don't think it will be in the future.

**Comment by kikin81** [comment]
thanks
