### ISSUE TITLE
Xcode 7 Warning - Address of NSLinkAttributeName will always evaluate to true

### ISSUE THREAD

**Issue by icecreammatt** [TTTAttributedLabel/TTTAttributedLabel#585]
I'm getting this warning in xcode. From what I can tell this if check is looking at the memory address of 
`UIKIT_EXTERN NSString * const NSLinkAttributeName NS_AVAILABLE(10_0, 7_0);                // NSURL (preferred) or NSString`

Is that the intent?

https://github.com/TTTAttributedLabel/TTTAttributedLabel/blob/master/TTTAttributedLabel/TTTAttributedLabel.m#L1178

![screen shot 2015-09-18 at 11 03 17 am](https://cloud.githubusercontent.com/assets/1154569/9966999/e93d1814-5df4-11e5-870a-deb297b0e9e6.png)

**Comment by getaaron** [comment]
`if (&NSLinkAttributeName)` checks at run-time whether `NSLinkAttributeName` is defined. Combined with the `__IPHONE_OS_VERSION_MAX_ALLOWED` check, this ensures the code isn't run on earlier versions of iOS because `&NSLinkAttributeName` will evaluate to `NO`.

**Comment by icecreammatt** [comment]
Thanks for the info. I suppressed the warnings on the file for now.

**Comment by MattiaConfalonieri** [comment]
Is possible simply ignore the warning? how can i suppress it? Thanks for help

**Comment by danipralea** [comment]
how did you suppressed the warning @getaaron ?

**Comment by icecreammatt** [comment]
If you go to the project build settings tab you can add a -w flag and that will hide the warnings. It's the same place you add the no-arc flag if you have had to do that before.

**Comment by icecreammatt** [comment]
I forgot to mention you add the flag directly to the file that has the warning.

**Comment by danipralea** [comment]
Thanks, but just removed the if clause, since there's already a check right before it for ios 7 and that type is defined for iOS 7

**Comment by jhersh** [comment]
> Thanks, but I just removed the if clause, since there's already a check right before it for ios 7 and that type is defined for iOS 7

:warning: This will crash apps compiled with the iOS 9 SDK running on iOS 6 or older devices.

**Comment by danipralea** [comment]
true. forgot about this scenario. Not my case though. Minimum supported version is iOS 7, so that's why I decided to go with it.

**Comment by ghennecke** [comment]
What about wrapping the `if (&NSLinkAttributeName)` with `#if __IPHONE_OS_VERSION_MIN_REQUIRED < 70000`?

**Comment by jadidian** [comment]
:+1:  this is the only warning I'm getting on a huge project with lots of external libraries, would love to see it gone... and thank you folks for the amazing work

**Comment by Stiian** [comment]
Still no official fix for this?

**Comment by VilemKurz** [comment]
Please do something with this. I can see a [pull request](https://github.com/TTTAttributedLabel/TTTAttributedLabel/pull/588), even passing checks, but not merged yet...

**Comment by zmorris** [comment]
I realize this is closed, but for anyone new to TTTAttributedLabel with CocoaPods, the easiest way to suppress the warning until the pull request is merged is to include the pod with:

pod 'TTTAttributedLabel', :inhibit_warnings => true

http://stackoverflow.com/a/13209057/539149

**Comment by OliverMahn-flinc** [comment]
@zmorris This is not closed, but you are right, best way ist to suppress the warning via pod file.

**Comment by wangruofeng** [comment]
you can just do this to make complier shutdown
 `#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wpointer-bool-conversion"
    if (&NSLinkAttributeName) {
#pragma clang diagnostic pop`

**Comment by icecreammatt** [comment]
Closing this as it is very stale and to clean out my issues list as I haven't done iOS dev in years.
