### ISSUE TITLE
Request for Comment: Drop support for iOS 4, 5, and 6

### ISSUE THREAD

**Issue by getaaron** [TTTAttributedLabel/TTTAttributedLabel#586]
I'm considering dropping support for iOS 4, 5, and 6.

This would allow:

- a shorter, more readable, more maintainable code base, bereft of compile and runtime checks for old symbol names and features
- modern Objective-C syntax

The current version would still exist on a separate branch.

While long-running backwards compatibility has been a hallmark of TTTAttributedLabel for some time, as @galambalazs points out, it may be mostly an academic exercise.

- Does anyone use `TTTAttributedLabel` in apps which support large numbers of iOS 4, 5, and 6 users? If so, can you share your data?
- One possible improvement with this change would be to delegate all drawing to `UILabel`, which would mostly end discrepancies between its appearance and this library's. This would remove some of the custom drawing features too. How would people feel about that?

I'll let this issue sit here for 4-6 weeks before moving forward.

**Comment by fraserscottmorrison** [comment]
Id say most active projects have dropped support for iOS6 already, so seems like a no brainer to me.

The minority could still access the legacy iOS4/5/6 branch so, in the name of progress, drop iOS6!

**Comment by senryxie** [comment]
As AppStore drops iOS 6 support a long time ago, it's safe to do so.
People who needs it can still use the supported branch to finish their work.

**Comment by jessesquires** [comment]
I say definitely drop iOS 6 and lower. However, I'd even push for being iOS 8+.

[Current stats](https://developer.apple.com/support/app-store/) show iOS 8 at 41% and iOS 9 at 52%. Even Apple recommends only supporting the 2 most recent OS versions.

Anyone on iOS 7 and earlier can simply pin to the current version.

**Comment by mpantiru** [comment]
I agree with @jessesquires, the same for me. At the moment I'm using it on an app iOS8+.

**Comment by galambalazs** [comment]
@jessesquires do it

**Comment by galambalazs** [comment]
I agree. 

iOS8+ is a solid foundation at this point.

The older version branch is not going away so people can still use it.

**Comment by vitalys** [comment]
Drop them all! :)
+1

**Comment by dapenggao** [comment]
> * a shorter, more readable, more maintainable code base, bereft of compile and runtime checks for old symbol names and features
> * modern Objective-C syntax

Definitely support this! The benefits greatly outweigh the costs.

**Comment by coverback** [comment]
At Ask.fm, we are using this library on iOS 7.1+. Dropping anything below 7.0 is not a problem for us for sure.
Dropping iOS 7 would be, as 11% of our DAU are using iOS 7.1 and the number dropped less than one percent point in the last month. iOS 9 release hasn't impacted the iOS 7 upgrade rate, unfortunately. Some of our top geos even have 20% of users on iOS 7. 

Despite that, we will be able to either backport or freeze on the older version. We rarely need new features (except for 3D Touch now), and this component is a very solid piece of work. We very rarely had to upgrade because of bugs.

**Comment by dreamcacher2014** [comment]
Drop them

**Comment by imagine4me** [comment]
drop 'em, 7+

**Comment by imaks** [comment]
I think dropping iOS 4-6 will be no problem at all, moreover old brach will still exist and anyone will still be able to use it. Dropping iOS 7 might negatively affect some apps that still support it, e.g. number of users on iOS 7 in our app is still 10% and this number didn't change with iOS 9 release. So, in my view, iOS 7+ is a good choice.

**Comment by andresgarza** [comment]
iOS 8+

**Comment by stefanomondino** [comment]
8+ for me...

**Comment by galambalazs** [comment]
@getaaron The issue has been open for 8 weeks now :)

**Comment by AnthonyMDev** [comment]
8+ for me as well.

I think it's pretty safe to drop support for anything below iOS 7 for sure. Most people are on 8+ by now.

**Comment by galambalazs** [comment]
Slack uses it too. iOS 8+ as well.

**Comment by getaaron** [comment]
I pushed some suggested changes to [`2.0.0`](https://github.com/TTTAttributedLabel/TTTAttributedLabel/tree/2.0.0). Let me know what you think so far. Still has a little ways to go but it should resolve nearly all of the drawing issues at the expense of old iOS incompatibility and some custom drawing features.

**Comment by Sh1mor1nka** [comment]
iOS 7+

**Comment by tungvoduc** [comment]
8+

**Comment by emobtech** [comment]
9+

**Comment by ZuYuanZhou** [comment]
8+

**Comment by loudnate** [comment]
8+

**Comment by p-antonelli** [comment]
7+

**Comment by ay8s** [comment]
8+

**Comment by jessesquires** [comment]
An update on current adoption rates ([apple](https://developer.apple.com/support/app-store/), [mixpanel](https://mixpanel.com/trends/#report/ios_9)).

* iOS 9 adoption: 71-82%
* iOS 8 adoption: 13-21%
* "Other": 4-8%

Also, we are now only 6-7 months away from WWDC and iOS 10.

**Comment by tmaes** [comment]
8+ for us

**Comment by jessesquires** [comment]
@getaaron - Is our consensus iOS 8+ here? Should we close?

**Comment by amayatsky** [comment]
8+

**Comment by getaaron** [comment]
@jessesquires The `2.0.0` branch is 8+ only.

**Comment by getaaron** [comment]
I'd prefer to keep this open until we have a 2.0.0 candidate — it can't hurt to continue collecting data. I don't feel strongly if you want to close it though.

**Comment by nartex** [comment]
8+

**Comment by akshaypakanati** [comment]
8+

**Comment by donnywals** [comment]
8+

**Comment by pixeldock** [comment]
8+

**Comment by tevghenii** [comment]
iOs 8+

**Comment by pjchavarria** [comment]
8+

**Comment by leonereveel** [comment]
8+
