### ISSUE TITLE
Scrolling performance issue

### ISSUE THREAD

**Issue by dev4dev** [TTTAttributedLabel/TTTAttributedLabel#590]
When a label contains around 80 lines of text and has enabled some dataDetectors

`self.textLabel.enabledTextCheckingTypes = NSTextCheckingTypeAddress | NSTextCheckingTypeLink | NSTextCheckingTypePhoneNumber;` 
Text contains about __6 links__.
The label is located inside of scroll view. There is noticeable delay before scroll starts. Here is profiler info.

<img width="650" alt="screenshot 2015-09-30 11 17 23" src="https://cloud.githubusercontent.com/assets/722407/10189346/1a53056a-6766-11e5-9a56-1f655b0d9d5a.png">

Could it be improved somehow? Because now it's unacceptable.

**Comment by getaaron** [comment]
- Are you up to date with `master`? If not, please try that since there have been some recent performance improvements..
- Is `extendsLinkTouchArea` set to `NO`? (`YES` will degrade performance.)

**Comment by dev4dev** [comment]
@getaaron no, I use latest version from CocoaPods and `extendsLinkTouchArea` is YES by default. 
Ok, I'll try later, for now I switched to UITextView. Thank you.

**Comment by getaaron** [comment]
@dev4dev I think this should resolve your issue then. The latest version on CocoaPods is not the latest version on `master`. Also, `extendsLinkTouchArea` is `NO` by default in the latest version.

**Comment by Sh1mor1nka** [comment]
So solution is not to use cocoapods? Because i also have the same issue.

**Comment by getaaron** [comment]
@Sh1mor1nka You could use `pod 'TTTAttributedLabel', :git => 'https://github.com/TTTAttributedLabel/TTTAttributedLabel.git'` — see [the docs](https://guides.cocoapods.org/using/the-podfile.html) for other syntax if you want to pull specific commits / newer code.
