### ISSUE TITLE
Does TTTAttributedLabel support NSBaselineOffsetAttributeName?

### ISSUE THREAD

**Issue by huy-le** [TTTAttributedLabel/TTTAttributedLabel#599]
I found that we don't support baselineAdjustment inside code documents. But does it do not support NSBaselineOffsetAttributeName for NSAttributedString too?

**Comment by mcstoufer** [comment]
+1 on this as well. I need to center some text inside a attributed string link using this lib.

**Comment by jx2** [comment]
+1 on adding this, please!

**Comment by jx2** [comment]
Adding link to pull request that adds support for NSBaselineOffsetAttributeName #604

**Comment by huy-le** [comment]
Thanks :D
