### ISSUE TITLE
Label's adjustsFontSizeToFitWidth does not work 

### ISSUE THREAD

**Issue by oferRounds** [TTTAttributedLabel/TTTAttributedLabel#606]
I use the following code:

`TTAttributedLabel *label = [[TTTAttributedLabel alloc] initWithFrame:frame];`
`label.adjustsFontSizeToFitWidth = YES;`
`label.minimumScaleFactor = 0.1;`
    
`label.attributedText = <some attributed string>`
`label.verticalAlignment = TTTAttributedLabelVerticalAlignmentTop;`
`label.lineBreakMode = NSLineBreakByWordWrapping;`
`label.numberOfLines = 5;`

but the text does not get adjusted when there's not enough space.
Is it maybe because I use an attributed string?

**Comment by christophercotton** [comment]
See this issue:  https://github.com/TTTAttributedLabel/TTTAttributedLabel/issues/564

**Comment by jessesquires** [comment]
Thanks @oferRounds / @christophercotton! :smile: 

Closing as dupe of #564

**Comment by oferRounds** [comment]
:+1:
