### ISSUE TITLE
Add `UI_APPEARANCE_SELECTOR` to `linkAttributes`, `activeLinkAttributes` and `inactiveLinkAttributes` properties.

### ISSUE THREAD

**Issue by vitalys** [TTTAttributedLabel/TTTAttributedLabel#609]
I'd like to add `UI_APPEARANCE_SELECTOR` to `linkAttributes`, `activeLinkAttributes` and `inactiveLinkAttributes` properties. I'm active user of `TTTAttributedLabel` and it's a bit strange, that I have to overwrite default settings for these properties in every place I'm using `TTTAttributedLabel`.
Are you ok we such improvement? If yes, I'll create a PR with changes/test.

Thanks

**Comment by getaaron** [comment]
This library doesn't currently support the appearance proxy, but a PR to add that would be welcome.
