### ISSUE TITLE
Xcode 7: warning: address of 'NSLinkAttributeName' will always evaluate to 'true'

### ISSUE THREAD

**Issue by AdrianFerreyra** [TTTAttributedLabel/TTTAttributedLabel#610]
When using this pod in Xcode 7, we're getting a warning about some if that always returns true.

`.../TTTAttributedLabel.m:1148:10: warning: address of 'NSLinkAttributeName' will always evaluate to 'true' [-Wpointer-bool-conversion]
    if (&NSLinkAttributeName) {
    ~~   ^~~~~~~~~~~~~~~~~~~`

Are you working on this warning?

thanks in advance!

**Comment by AnthonyMDev** [comment]
+1 getting this same warning.

**Comment by jhersh** [comment]
#585, #588
