### ISSUE TITLE
Links not working when label is in a scrollview

### ISSUE THREAD

**Issue by halpz** [TTTAttributedLabel/TTTAttributedLabel#611]
didSelectLinkWithURL is not invoked when tapping a link, (the link color changes as if it has been pressed, but no action comes from it).

**Comment by blmyself** [comment]
me too. It seems that no body reply issues.

**Comment by getaaron** [comment]
Have you set `delegate`? Have you had a chance to set a breakpoint and investigate why it's not called? The delegate method is called correctly in the sample project.

**Comment by halpz** [comment]
yes, it seems to happen when I add the label as a subview of my UIScrollView's content view

**Comment by halpz** [comment]
I don;t know where to breakpoint as no action is triggered

**Comment by getaaron** [comment]
Sounds like another gesture recognizer might be cancelling the touch. Try setting breakpoints in touchesBegan:withEvent:, touchesMoved:withEvent:, touchesEnded:withEvent:, and touchesCancelled:withEvent: and see what happens.

**Comment by josipbernat** [comment]
Did someone find solution for this? This problem occurs on iOS 10 too.

**Comment by yoimhere** [comment]
me too

**Comment by yoimhere** [comment]
me too

**Comment by josipbernat** [comment]
I had UITapGestureRecognizer on UIScrollView. After removing it my problem was solved.
