### ISSUE TITLE
Warning when building 

### ISSUE THREAD

**Issue by AnthonyMDev** [TTTAttributedLabel/TTTAttributedLabel#614]
I get the following warning when building the library as a Cocoapod dependency in my application

    xcodebuild:  TTTAttributedLabel/TTTAttributedLabel/TTTAttributedLabel.m:1148:10: warning: address of 'NSLinkAttributeName' will always evaluate to 'true' [-Wpointer-bool-conversion]

**Comment by jhersh** [comment]
#585 #588

**Comment by AnthonyMDev** [comment]
Thanks. I tried to find an open issue for this, but must have missed them. Sorry!
