### ISSUE TITLE
pod update failed when set TTTAttributedLabel ~>2.0.0

### ISSUE THREAD

**Issue by qianyanseu** [TTTAttributedLabel/TTTAttributedLabel#623]
My pod version is 0.39.0

Also, pod search cannot find the latest version.
![b297123c-3ddd-4aef-9e42-ce4621af3b96](https://cloud.githubusercontent.com/assets/1569368/12001602/7a5d43cc-ab26-11e5-983f-7cabff44001b.jpg)

This is my pod file

```
platform :ios, '7.0'
inhibit_all_warnings!
xcodeproj 'CBWallet4iPhone'

target :CBWallet4iPhone do
    
    pod 'SMPageControl', '~> 1.2'
    pod 'FMDB', '~> 2.2'
    pod 'SDWebImage', '~> 3.5.2'
    pod 'RegexKitLite', '~> 4.0'
    pod 'libqrencode', '~> 3.4.2'
    pod 'ZBarSDK', '~> 1.3.1'
    pod 'MJRefresh'
    pod 'pop'
    pod 'FIR.im', '~> 1.2.0' , :configurations => ['Debug']
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    pod 'CRToast', '~> 0.0.7'
    pod 'Masonry'
    pod 'MQTTKit', :git => 'https://github.com/mobile-web-messaging/MQTTKit.git'
    pod 'TTTAttributedLabel'
end


post_install do |installer|
installer.pods_project.targets.each do |target|
puts "#{target.name}"
end
end
```

Any clues would be appreciated. Thanks!

**Comment by getaaron** [comment]
2.0.0 is still in development on the `2.0.0` branch, but it's not ready for production use in an app yet. You could try:

    pod 'TTTAttributedLabel', :git => 'https://github.com/TTTAttributedLabel/TTTAttributedLabel.git'

If you want the latest code from the `master` branch, which is a little bit newer than the latest CocoaPods version.

**Comment by qianyanseu** [comment]
Thanks. I'll close this issue.
