### ISSUE TITLE
Multiline TTTAttributedLabel with hyperlinks

### ISSUE THREAD

**Issue by siberianisaev** [TTTAttributedLabel/TTTAttributedLabel#624]
UITableViewCell contain TTTAttributedLabel with html text.
Cell height calculated automatically (UITableViewAutomaticDimension).

I found that if label text is big (for example cell height > table view height) 
AND text contains two or more hyperlinks, then table view scrolling will not be smooth (shows text part by parts with delay). 

I removed hyperlinks from this text (text lenght has not changed too much) and tried again - scrolling was ok (smooth). 
So looks like hyperlinks detection going on main tread and blocked UI.

I tested on iOS9

**Comment by getaaron** [comment]
Did you try the latest code? Do you have the link radius detection disabled?

**Comment by siberianisaev** [comment]
Yes, exactly this.
I used default state of 'extendsLinkTouchArea' flag.
Thanks @getaaron
