### ISSUE TITLE
TVOS Support?

### ISSUE THREAD

**Issue by mariohahn** [TTTAttributedLabel/TTTAttributedLabel#630]
You haven't updated your Podspec to cocoapods.

https://github.com/CocoaPods/Specs/blob/master/Specs/TTTAttributedLabel

**Comment by mariohahn** [comment]
Any news about that? 🙃

**Comment by jessesquires** [comment]
Hey @mariohahn :smile: 

Planning this for 2.0

**Comment by jessesquires** [comment]
looks like this is done 😄
