### ISSUE TITLE
crash when setText in background thread

### ISSUE THREAD

**Issue by wells1013** [TTTAttributedLabel/TTTAttributedLabel#636]
![abc](https://cloud.githubusercontent.com/assets/5172252/12347535/9a8b724e-bb99-11e5-96f2-a4943c67e6a6.png)

crash at method 
- (void)drawFramesetter:(CTFramesetterRef)framesetter
       attributedString:(NSAttributedString *)attributedString
              textRange:(CFRange)textRange
                 inRect:(CGRect)rect
                context:(CGContextRef)c

**Comment by jessesquires** [comment]
thanks @wells1013 !

------
notes from [docs](https://developer.apple.com/library/ios/documentation/StringsTextFonts/Conceptual/CoreText_Programming/Overview/Overview.html):
>Core Text functions may be invoked from multiple threads simultaneously provided that the client is not mutating any parameters such as attributed strings that are shared between threads.

**Comment by getaaron** [comment]
Is there a reason to support this as a feature? UI work typically should be done on the main thread. Also, this method is removed in the 2.0.0 branch.

**Comment by segiddins** [comment]
Closing due to @getaaron's comment.

**Comment by getaaron** [comment]
Thanks, @segiddons. Let me know if you're interested in picking up the 2.0 branch. I lost steam with it since nobody else seemed to be interested.

**Comment by segiddins** [comment]
@getaaron released https://github.com/TTTAttributedLabel/TTTAttributedLabel/releases/tag/2.0.0

**Comment by getaaron** [comment]
@segiddins I meant the unfinished work in https://github.com/TTTAttributedLabel/TTTAttributedLabel/tree/2.0.0?files=1 – to allow `UILabel` to handle the drawing work, so there wouldn't be all these discrepancies with how `TTTAttributedLabel` draws, and it would support more advanced features like `NSTextAttachment`.

**Comment by segiddins** [comment]
Ah, didn't know about that -- likely not going to be able to
