### ISSUE TITLE
Warning when pushing Cocoapods with dependency on TTTAttributedLabel

### ISSUE THREAD

**Issue by AnthonyMDev** [TTTAttributedLabel/TTTAttributedLabel#637]
When trying to push my pod, I get the following warning.

    - WARN  | xcodebuild:  TTTAttributedLabel/TTTAttributedLabel/TTTAttributedLabel.m:1148:10: warning: address of 'NSLinkAttributeName' will always evaluate to 'true' [-Wpointer-bool-conversion]

I can still push my pod by using the `--allow-warnings` flag, but I figured you should be aware of this issue.

Thanks

**Comment by jessesquires** [comment]
Thanks! We'll get this fixed for 2.0

**Comment by jhersh** [comment]
#585 #588
