### ISSUE TITLE
Using TTTAttributedLabel in iOS6，it will crash for the  NSUnderlineColorAttributeName 

### ISSUE THREAD

**Issue by lmeo** [TTTAttributedLabel/TTTAttributedLabel#639]

**Comment by lmeo** [comment]
Er,the API is dropped support for iOS6.

**Comment by Coeur** [comment]
The podspec doesn't document this drop of support. It reads `s.ios.deployment_target = '4.3'`

**Comment by jessesquires** [comment]
as of v2.0 we only support iOS 8 and above.

**Comment by Coeur** [comment]
@jessesquires @segiddins, may you keep a 1.x branch for older iOS targets? I'm OK to help for crash issues.
