### ISSUE TITLE
Update releases/podspec to include fixes since 1.13.4?

### ISSUE THREAD

**Issue by gregpassmore** [TTTAttributedLabel/TTTAttributedLabel#640]
I need the critical fix that fixes the UI hang with dispatch_sync vs dispatch_async that was included in pull request 565

**Comment by joshfriend** [comment]
Fixes from #549 would also be nice :)

**Comment by Coeur** [comment]
Note that in your Podfile you can use this to get the latest commit from 14th Dec 2015:

    pod 'TTTAttributedLabel', :git => 'https://github.com/TTTAttributedLabel/TTTAttributedLabel.git', :commit => '8a56d49263843ac4a55003e711da25662ff11c07'

**Comment by rex-remind101** [comment]
+1000000000

**Comment by jhersh** [comment]
#665
