### ISSUE TITLE
can't use NSTextAttachment replace image

### ISSUE THREAD

**Issue by qiaoxiyang** [TTTAttributedLabel/TTTAttributedLabel#641]
when I use NSMutableAttributedString,I can't use NSTextAttachment replace image

**Comment by getaaron** [comment]
NSTextAttachment is not currently supported. You can try the 2.0.0 branch where it works but some other features are incomplete.

**Comment by getaaron** [comment]
BTW, if you try it out, pull requests to 2.0.0 are welcome!
