### ISSUE TITLE
Carthage support does not work

### ISSUE THREAD

**Issue by mathiasnagler** [TTTAttributedLabel/TTTAttributedLabel#642]
I am trying to add `TTTAttributedLabel` to my project via `carthage` but it does not seem to work. I am using the current version of `carthage` `0.12.0`. Here is my `Cartfile`:

```github "TTTAttributedLabel/TTTAttributedLabel"```

Unfortunately i get this error:

```
*** Fetching TTTAttributedLabel
*** Checking out TTTAttributedLabel at "1.13.4"
*** Skipped building TTTAttributedLabel due to the error:
Dependency "TTTAttributedLabel" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/TTTAttributedLabel/TTTAttributedLabel/issues/new
```

I checked the `.xcodeproj` that comes with `TTTAttributedLabel` and there definitely is a shared framework scheme but carthage does not seem to find it.

**Comment by mathiasnagler** [comment]
The issue should be resolved by https://github.com/Carthage/Carthage/pull/1099.

**Comment by getaaron** [comment]
Thank you for the investigation, @mathiasnagler.
