### ISSUE TITLE
Link not clickable

### ISSUE THREAD

**Issue by joaopedrok** [TTTAttributedLabel/TTTAttributedLabel#647]
Im using this component and when a i add a link it recognizes the link and i can't click. Other problem is that im trying do add a link to my truncation token and it is not working. It does not even recognizes my truncation token as  a link. See the following code:

 let seeMoreText = NSLocalizedString("... See more" , comment : "")

 self.descriptionText.enabledTextCheckingTypes = NSTextCheckingType.Link.rawValue
 let attributedTokenString = NSMutableAttributedString(string: seeMoreText, attributes: [NSFontAttributeName : UIFont(name: "HelveticaNeue-BoldItalic",size: 10.0)! , NSForegroundColorAttributeName : UIColor.whiteColor() , NSLinkAttributeName : NSURL(string: "http://www.google.com.br")!])
        
self.descriptionText.attributedTruncationToken = attributedTokenString
self.descriptionText.delegate = self
self.descriptionText.userInteractionEnabled = true

Does Anyone know what is going on?

**Comment by imerkulov** [comment]
@joaopedrok 

I had the same one. Label detected links, but they were not clickable.

I had UICollectionView and cells with TTTAttributedLabel. Also I have UITapGestureRecognizer on the collection view and it broke all my links. 

I've fixed this problem when set property cancelsTouchesInView = NO for gesture recognizer.

I hope it will help you.

**Comment by getaaron** [comment]
Something in your view hierarchy is intercepting the touch event. Could be a gesture recognizer or any other view higher up in the responder chain.

**Comment by joaopedrok** [comment]
So, i have a TapGesture in my cell. It is a UICollectionView and inside this view i have a tap gesture. But i can see the link, i can see the event of clicking but it doesnt work. There is no way to do that even with this tap gesture?

**Comment by getaaron** [comment]
It might be worth setting breakpoints inside the label to see what isn't working as you expect. As it stands, I don't have enough information to debug the issue.
