### ISSUE TITLE
超长文本时大量消耗内存导致crash

### ISSUE THREAD

**Issue by keshiim** [TTTAttributedLabel/TTTAttributedLabel#656]
hi~，你好，请原谅我不能用纯英语交流，但是有一个问题我们已经忍受好久了。在IM聊天列表中用的UITableViewCell中引用了TTT，输入超长文本（其中有链接），滑动TableView会导致内存暴涨，程序崩溃，希望能够得到妥善处理

**Comment by yas375** [comment]
@keshiim дружище, а ты уверен, что все правильно делаешь?

**Comment by yangzheng006** [comment]
应该是你自己程序的问题，我也在tableview中用到过TTT

**Comment by keshiim** [comment]
@yas375 sorry about that, actually it`s indeed my app issue.o(╯□╰)o

**Comment by keshiim** [comment]
@yangzheng006 是我程序的问题，造成的。
