### ISSUE TITLE
Dont' support autolayout

### ISSUE THREAD

**Issue by GeniusBrother** [TTTAttributedLabel/TTTAttributedLabel#657]
The following is a comparison between cocoa and  TTTAttributedLabel, but TTTAttributedLabel don't work!

NSString *text = @"本文为博主原创文章,NSMakeRange本文为博主原创文章,NSMakeRange本文为博主原创文章文为博主原创文文为博主原创文文为博主原创文文为博主原创文文为博主原创文";
    NSMutableAttributedString *attribute = [[NSMutableAttributedString alloc] initWithString:text attributes:@{NSFontAttributeName:[UIFont systemFontOfSize:17],NSKernAttributeName:@2}];
    UILabel *label = [[UILabel alloc] initWithFrame:CGRectZero];
    label.numberOfLines = 3;
    label.backgroundColor = [UIColor redColor];
    label.attributedText  = attribute;
    [self.view addSubview:label];
    [label mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerX.equalTo(@0);
        make.top.equalTo(@100);
        make.width.lessThanOrEqualTo(@300);
    }];

    TTTAttributedLabel *tlabel = [[TTTAttributedLabel alloc] initWithFrame:CGRectZero];
    tlabel.numberOfLines = 3;
    tlabel.font = [UIFont systemFontOfSize:17];
    tlabel.backgroundColor = [UIColor redColor];
    [tlabel setText:text];
    [self.view addSubview:tlabel];
    [tlabel mas_makeConstraints:^(MASConstraintMaker *make) {
        make.center.equalTo(@0);
        make.width.lessThanOrEqualTo(@300);
    }];

**Comment by GeniusBrother** [comment]
i have found the method to solve this problem use preferredMaxLayoutWidth

**Comment by lethianqt94** [comment]
Can you show me some code? I can't use it width autolayout. Too bad!

**Comment by GeniusBrother** [comment]
as I mentioned above, you can use preferredMaxLayoutWidth, not make.width.lessThanOrEqualTo(@300);
