### ISSUE TITLE
Hyperlink is tapped when I click outside text with link

### ISSUE THREAD

**Issue by NastyAlloys** [TTTAttributedLabel/TTTAttributedLabel#659]
I have NSAttributedString in my label which is with and without hyperlink. When I click on the area without text or where text is without link, the nearest text with link is tapped.

I tried use `UITapGestureRecogniser.shouldReceiveTouch` where i checked `self.descriptionLabel.containslinkAtPoint(touch.locationInView(self.descriptionLabel))` but it didn't work for me.

How I can solve this problem?

**Comment by jhersh** [comment]
Set `extendsLinkTouchArea` to `NO`.

**Comment by NastyAlloys** [comment]
@jhersh you're my life saver! Thx!
