### ISSUE TITLE
Bug when adding link to truncation attributed string

### ISSUE THREAD

**Issue by luisfuertes** [TTTAttributedLabel/TTTAttributedLabel#663]
Hi, i have the same issue that:
https://github.com/TTTAttributedLabel/TTTAttributedLabel/issues/519#

I think it was fixed on this link
https://github.com/TTTAttributedLabel/TTTAttributedLabel/commit/f243cc5191131418e4fd27da456578834315b391

But the last version doesnt have that fix. I tried to download that commit, but when text end with \n the link of truncation attributed string doesnt run.

Any idea? Thanks!

**Comment by uwjimmyxu** [comment]
I'm also having issues with truncation. The link seems to be added to the characters immediate before the truncation text at times - so tapping on the truncation text doesn't do anything. This appears to only affect the tap area of the link and not the actual visual styling of the text.

**Comment by jessesquires** [comment]
looks like this should be included in 2.0.0

**Comment by puneet-1106** [comment]
@jessesquires Hi is this bug get resolve???I am downloading the latest sample..but still gets problem.

**Comment by coal175** [comment]
Hello is there a fix for this?  I amrunning into the same problem.

**Comment by ajfigueroa** [comment]
The issue is still present in 2.0.0. 
It's reproducible if you press and hold slightly to the left (assuming LTR text) of the the truncation token.

**Comment by veila** [comment]
Pls fix this error

**Comment by mendaparadarshit** [comment]
Solved this issue: https://github.com/TTTAttributedLabel/TTTAttributedLabel/issues/519#issuecomment-752873366
