### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by rex-remind101** [TTTAttributedLabel/TTTAttributedLabel#665]
Last version update was June 15, 2015. Looks like there's been quite a bit of work since then, including bug fixes, could a new version be added please?

**Comment by Coeur** [comment]
Duplicate of https://github.com/TTTAttributedLabel/TTTAttributedLabel/issues/640

**Comment by Coeur** [comment]
Note that in your Podfile you can use this to get the latest commit from 14th Dec 2015:

    pod 'TTTAttributedLabel', :git => 'https://github.com/TTTAttributedLabel/TTTAttributedLabel.git', :commit => '8a56d49263843ac4a55003e711da25662ff11c07'

**Comment by rex-remind101** [comment]
I prefer official releases since they're easier to pass code review.

**Comment by Coeur** [comment]
@rex-remind101 as TTTAttributedLabel has many old issues and many pending pull requests more than 6 month old, I would advice trying https://github.com/Krelborn/KILabel which is an active project.

**Comment by xilin** [comment]
@Coeur It seems that KILabel is also not active. The last commit is Commits on May 26, 2015.

**Comment by Coeur** [comment]
@xilin Correct. Too bad we can't see [the forks](https://github.com/TTTAttributedLabel/TTTAttributedLabel/network).

**Comment by xilin** [comment]
@Coeur We can see the forks through github api: https://api.github.com/repos/TTTAttributedLabel/TTTAttributedLabel/forks

The Chinese fork you mentioned is quite interesting since I see a commit log in Chinese pinyi 'MD'...

**Comment by Coeur** [comment]
off-topic: seems fealonelei, you and me are all three from the same city. 😄

**Comment by rex-remind101** [comment]
@Coeur are you saying that this repo is no longer being versioned? Can't we just ping someone with push access? Seems like @jhersh most recently created a tag.

**Comment by xilin** [comment]
@Coeur I've attended the Cocoahead meetup serveral times :)

**Comment by jhersh** [comment]
I'm no longer able to maintain TTTAttributedLabel and @jessesquires has a lot going on as well. We'd be interested in bringing on at least one more maintainer. There's a lot of low-hanging fruit and easy wins. If anyone's interested, do let us know.

**Comment by Coeur** [comment]
jhersh, thank you for your followup. I would like to help, especially for:
* the alignment issue
* the crashes
* the pending pull requests
* the ability to use both `setText:` and `setAttributedText:`

But I would also like to see a Swift equivalent and a drop of some old iOS versions.

**Comment by segiddins** [comment]
I just released 2.0! https://github.com/TTTAttributedLabel/TTTAttributedLabel/releases/tag/2.0.0

**Comment by rex-remind101** [comment]
:boom: thank you @segiddins !
