### ISSUE TITLE
TTTAL objects don't appear in accessibility hierarchy for XCUITest

### ISSUE THREAD

**Issue by AaronSofaer** [TTTAttributedLabel/TTTAttributedLabel#681]
I have a TTTAttributedLabel that I've created in a .xib file (or rather, that a developer has created in a .xib file; I'm just writing test automation here). The TTAL has, in the xib, an accessibilityIdentifier set and the staticTexts box checked, as do two other UILabels on the tableview cell in question.

Upon running the program / the tests, both of the other UILabels appear in the accessibility hierarchy under their accessibilityIdentifiers as StaticTexts, and I can assert with regards to their state. The TTTAttributedLabel does not; it appears nowhere in the hierarchy in any form.

If this is not a known issue, I could spend some more time debugging this and possibly file a pull request, but I thought I'd bring it up and ask if there's something obvious / already known that I'm missing.

**Comment by jhersh** [comment]
TTTAttributedLabel itself is not an accessible element, though any links appearing in the label will be. This is as designed; if you need custom behavior here you should subclass and override the `UIAccessibilityElement ` methods.

**Comment by AaronSofaer** [comment]
@jhersh Thank you for answering, will go ahead and do exactly that. :)

**Comment by russbishop** [comment]
From the described behavior in the docs it seems like VoiceOver won't ever read the non-link text in a label which is incorrect behavior. I might be missing something about this though...

**Comment by jessesquires** [comment]
thanks @russbishop ! 😊

**Comment by raymondlapak** [comment]
Hello, are you still facing this error @AaronSofaer ?

I just recently bumped into this issue as I am trying to automate test using XCUITest. The XCUITest complaints that

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString absoluteString]: unrecognized selector sent to instance 0x608000310ce0'
First throw call stack:
(
	0   CoreFoundation                      0x000000010535f34b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010b11e21e objc_exception_throw + 48
	2   CoreFoundation                      0x00000001053cef34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00000001052e4c15 ___forwarding___ + 1013
	4   CoreFoundation                      0x00000001052e4798 _CF_forwarding_prep_0 + 120
	***5   bl_ios                              0x0000000101a42fa0 -[TTTAttributedLabelLink accessibilityValue] + 288***
	***6   bl_ios                              0x0000000101a3cb47 -[TTTAttributedLabel accessibilityElements] + 1495***
	***7   bl_ios                              0x0000000101a3c43b -[TTTAttributedLabel accessibilityElementCount] + 43***

**Comment by AaronSofaer** [comment]
@raymondlapak that is a different problem than the one that I had and I recommend you file it in a different Issue.
