### ISSUE TITLE
ITMS-90809: Deprecated API Usage (UIWebView)

### ISSUE THREAD

**Issue by svetlanama** [TTTAttributedLabel/TTTAttributedLabel#810]
Could you remove/replace **UIWebView** pls 

[https://github.com/TTTAttributedLabel/TTTAttributedLabel/blob/b0f1f93d5d4368a7aaf52e848013a1b40b00dc3c/TTTAttributedLabel/TTTAttributedLabel.h#L166](https://github.com/TTTAttributedLabel/TTTAttributedLabel/blob/b0f1f93d5d4368a7aaf52e848013a1b40b00dc3c/TTTAttributedLabel/TTTAttributedLabel.h#L166)

```
Apple recognises this line as an issue:
ITMS-90809: Deprecated API Usage - Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability. 
```

**Comment by Vnox** [comment]
I have the same problem!

**Comment by ergunkocak** [comment]
@svetlanama  Is it really the case? Isnt it just a comment? Did you find a solution?

**Comment by svetlanama** [comment]
@ergunkocak  yes, this is a real case. I checked everything in my project include dependencies and this is only one place - it is a comment. Yeah just remove the comment, or replace `UIWebView` to `WKWebView`. This should be enough. Thanks!

**Comment by svetlanama** [comment]
@ergunkocak btw, provided PR https://github.com/TTTAttributedLabel/TTTAttributedLabel/pull/812

**Comment by kvdesa** [comment]
Same is happening with me, please accept and merge the PR.

**Comment by neljaj** [comment]
Yep... I also have this issue.  Would really appreciate an update.  Can someone please accept and merge.

**Comment by vapor-pawelw** [comment]
This is correct, AppAuth lib had exactly the same issue and fixed it - some refs below
https://github.com/openid/AppAuth-iOS/releases/tag/1.3.1
https://github.com/openid/AppAuth-iOS/issues/449
