### ISSUE TITLE
TTTAttributedLabel w/ XCUITest not Tapable

### ISSUE THREAD

**Issue by BolideRider** [TTTAttributedLabel/TTTAttributedLabel#811]
I subclassed TTTAttributedLabel overriding var isAccessibilityElement and isAccessibilityElement(), then assigned it an accessibilityIdentifier and accessibilityLabel == text, so it would appear in the view hierarchy of a UIAutomationTest. I have no issues grabbing the text from the label in a UITest, but I have assigned a link while using linkTapBlock{}, and when calling tap() on the XCUIElement it does not respond. Is there something else I need to override? The call block is never executed on tap().

`availableBalanceTitleLabel.setText(attributedText)
    availableBalanceTitleLabel.linkAttributes = linkAttributes
    availableBalanceTitleLabel.activeLinkAttributes = activeLinkAttributes
    availableBalanceTitleLabel.accessibilityIdentifier = "XCAvailableBalanceTitleLabel"
    availableBalanceTitleLabel.accessibilityLabel = attributedText.string

    let result = availableBalanceTitleLabel.addLink(to: url, with: range)
    result?.linkTapBlock = { (label: TTTAttributedLabel?, link: TTTAttributedLabelLink?) -> Void in
        DispatchQueue.main.async(execute: {
            self.delegate?.availableBalanceTitleLabelTapped()
        })
    }`

**Comment by eugenDrobov** [comment]
@BolideRider  How did you resolve this?

**Comment by Edf2w5** [comment]
😄
