### ISSUE TITLE
Emoji renders incorrectly

### ISSUE THREAD

**Issue by tonymillion** [TTTAttributedLabel/TTTAttributedLabel#82]
Hi, I've been trying to replace UILabel with TTTAttributedLabel so I can lankily URLS, I came across a weird edge-case involving emoji, I don't know if its indicative of a "larger problem", but might be worth looking at.

background: This is a tableview in which the cells contains a UILabel, in 

```
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath
```

I calculate the height of the cell using the following:

```

                CGSize requiredSize = [text sizeWithFont:[UIFont fontWithName:@"American Typewriter" size:17]
                                       constrainedToSize:CGSizeMake(POST_WIDTH, CGFLOAT_MAX)
                                           lineBreakMode:UILineBreakModeWordWrap];

                return 30 + requiredSize.height + 10;
```

(30 for the header + the required label height + 10 for the footer).

This works fine for UILabel and TTTAttributedLabel as long as they're displaying "plain text". As soon as the text contains an emoji the UILabel continues to render correctly, however the TTAttributedLabel no longer renders anything!  (i.e. _the TTTAttributedLabel view is completely "empty" as if nothing was rendered into it_).

If I change the +10 to +16 (i.e to _add an extra 6 pixels to the label_) the text then renders properly, except with extra whitespace.

Initial investigation shows that the text is being rendered differently (some screenshots):

**UILabel:**
![uilabel](http://tonymillion.com/uilabel.png)

**TTTAttributedLabel**
![uilabel](http://tonymillion.com/tttattributedlabel.png)

Notice how the Emoji is rendered vertically centred on the UILabel, but baseline on the TTTAttributedLabel?

I don't have a solution just yet - I'll report back any findings but I wanted to log the issue incase you already know how to fix it!

**Comment by jpsison29** [comment]
Just add textinset 

`chatTextLabel.textInsets = UIEdgeInsetsMake(1.5, 0, 1.5, 0)`
